// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { ResolvingMetadata, ResolvingViewport } from 'next/types.js';
import type { AppRoutes, LayoutRoutes, ParamMap } from './routes.js';

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
	default: // biome-ignore lint/suspicious/noExplicitAny: Next.js generated type
		| React.ComponentType<{ params: Promise<ParamMap[Route]> } & any>
		| ((
				// biome-ignore lint/suspicious/noExplicitAny: Next.js generated type
				props: { params: Promise<ParamMap[Route]> } & any,
		  ) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>);
	// biome-ignore lint/suspicious/noExplicitAny: Next.js generated type
	generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[];
	generateMetadata?: (
		// biome-ignore lint/suspicious/noExplicitAny: Next.js generated type
		props: { params: Promise<ParamMap[Route]> } & any,
		parent: ResolvingMetadata,
		// biome-ignore lint/suspicious/noExplicitAny: Next.js generated type
	) => Promise<any> | any;
	generateViewport?: (
		// biome-ignore lint/suspicious/noExplicitAny: Next.js generated type
		props: { params: Promise<ParamMap[Route]> } & any,
		parent: ResolvingViewport,
		// biome-ignore lint/suspicious/noExplicitAny: Next.js generated type
	) => Promise<any> | any;
	// biome-ignore lint/suspicious/noExplicitAny: Next.js generated type
	metadata?: any;
	// biome-ignore lint/suspicious/noExplicitAny: Next.js generated type
	viewport?: any;
};

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
	default:
		| React.ComponentType<LayoutProps<Route>>
		| ((
				props: LayoutProps<Route>,
		  ) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>);
	// biome-ignore lint/suspicious/noExplicitAny: Next.js generated type
	generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[];
	generateMetadata?: (
		// biome-ignore lint/suspicious/noExplicitAny: Next.js generated type
		props: { params: Promise<ParamMap[Route]> } & any,
		parent: ResolvingMetadata,
		// biome-ignore lint/suspicious/noExplicitAny: Next.js generated type
	) => Promise<any> | any;
	generateViewport?: (
		// biome-ignore lint/suspicious/noExplicitAny: Next.js generated type
		props: { params: Promise<ParamMap[Route]> } & any,
		parent: ResolvingViewport,
		// biome-ignore lint/suspicious/noExplicitAny: Next.js generated type
	) => Promise<any> | any;
	// biome-ignore lint/suspicious/noExplicitAny: Next.js generated type
	metadata?: any;
	// biome-ignore lint/suspicious/noExplicitAny: Next.js generated type
	viewport?: any;
};

// Validate ../../app/page.tsx
{
	type __IsExpected<Specific extends AppPageConfig<'/'>> = Specific;
	const handler = {} as typeof import('../../../apps/web/app/page.js');
	type __Check = __IsExpected<typeof handler>;
	// @ts-ignore
	type __Unused = __Check;
}

// Validate ../../app/layout.tsx
{
	type __IsExpected<Specific extends LayoutConfig<'/'>> = Specific;
	const handler = {} as typeof import('../../../apps/web/app/layout.js');
	type __Check = __IsExpected<typeof handler>;
	// @ts-ignore
	type __Unused = __Check;
}
