'use client';

import type React from 'react';

/**
 * Minimal text field prop contract required by the shared employee code field.
 */
export interface EmployeeCodeTextFieldProps {
	/** Visible field label. */
	label: string;
	/** Optional field orientation. */
	orientation?: 'vertical' | 'horizontal';
	/** Whether the field should be disabled. */
	disabled?: boolean;
	/** Optional value transformer fired on text changes. */
	onValueChange?: (nextValue: string) => string;
}

/**
 * Minimal field renderer contract exposed by TanStack form field helpers.
 */
export interface EmployeeCodeFieldRenderer {
	/** Shared text field renderer. */
	TextField: (props: EmployeeCodeTextFieldProps) => React.ReactElement;
}

/**
 * Props for the shared employee code field.
 */
export interface EmployeeCodeFieldProps {
	/** Field renderer returned by the form library. */
	field: EmployeeCodeFieldRenderer;
	/** Localized field label. */
	label: string;
	/** Whether the form is currently editing an existing employee. */
	isEditMode: boolean;
	/** Tracks when the user overrides the autogenerated code. */
	setHasCustomCode: React.Dispatch<React.SetStateAction<boolean>>;
	/** Optional field orientation. */
	orientation?: 'vertical' | 'horizontal';
}

/**
 * Renders the shared employee code field used by desktop and mobile employee forms.
 *
 * @param props - Component props
 * @returns Employee code field JSX
 */
export function EmployeeCodeField({
	field,
	label,
	isEditMode,
	setHasCustomCode,
	orientation,
}: EmployeeCodeFieldProps): React.ReactElement {
	/**
	 * Marks the employee code as manually overridden.
	 *
	 * @param nextValue - Next field value
	 * @returns Unchanged field value
	 */
	const handleValueChange = (nextValue: string): string => {
		if (!isEditMode) {
			setHasCustomCode(true);
		}

		return nextValue;
	};

	return (
		<field.TextField
			label={label}
			orientation={orientation}
			disabled={isEditMode}
			onValueChange={handleValueChange}
		/>
	);
}
