import { relations } from 'drizzle-orm';
import {
	boolean,
	doublePrecision,
	index,
	integer,
	jsonb,
	numeric,
	pgEnum,
	pgTable,
	text,
	time,
	timestamp,
	uniqueIndex,
} from 'drizzle-orm/pg-core';
import { randomUUID } from 'node:crypto';

// ============================================================================
// Auth Tables (Managed by BetterAuth)
// ============================================================================

/**
 * User table - stores user account information.
 * Extended with admin plugin fields for role management and banning.
 */
export const user = pgTable('user', {
	id: text('id').primaryKey(),
	name: text('name').notNull(),
	email: text('email').notNull().unique(),
	emailVerified: boolean('email_verified').default(false).notNull(),
	image: text('image'),
	createdAt: timestamp('created_at').defaultNow().notNull(),
	updatedAt: timestamp('updated_at')
		.defaultNow()
		.$onUpdate(() => /* @__PURE__ */ new Date())
		.notNull(),
	/** User role for admin plugin (e.g., 'user', 'admin') */
	role: text('role').default('user'),
	/** Whether the user is banned from the system */
	banned: boolean('banned').default(false),
	/** Reason for banning the user */
	banReason: text('ban_reason'),
	/** When the ban expires (null = permanent) */
	banExpires: timestamp('ban_expires'),
	/** Unique username for the user */
	username: text('username').unique(),
	/** Display username (can differ from username) */
	displayUsername: text('display_username'),
});

/**
 * Session table - stores user session information.
 * Extended with admin and organization plugin fields.
 */
export const session = pgTable(
	'session',
	{
		id: text('id').primaryKey(),
		expiresAt: timestamp('expires_at').notNull(),
		token: text('token').notNull().unique(),
		createdAt: timestamp('created_at').defaultNow().notNull(),
		updatedAt: timestamp('updated_at')
			.$onUpdate(() => /* @__PURE__ */ new Date())
			.notNull(),
		ipAddress: text('ip_address'),
		userAgent: text('user_agent'),
		userId: text('user_id')
			.notNull()
			.references(() => user.id, { onDelete: 'cascade' }),
		/** Admin user ID if this session is impersonating another user */
		impersonatedBy: text('impersonated_by'),
		/** Currently active organization ID for organization plugin */
		activeOrganizationId: text('active_organization_id'),
	},
	(table) => [index('session_userId_idx').on(table.userId)],
);

export const account = pgTable(
	'account',
	{
		id: text('id').primaryKey(),
		accountId: text('account_id').notNull(),
		providerId: text('provider_id').notNull(),
		userId: text('user_id')
			.notNull()
			.references(() => user.id, { onDelete: 'cascade' }),
		accessToken: text('access_token'),
		refreshToken: text('refresh_token'),
		idToken: text('id_token'),
		accessTokenExpiresAt: timestamp('access_token_expires_at'),
		refreshTokenExpiresAt: timestamp('refresh_token_expires_at'),
		scope: text('scope'),
		password: text('password'),
		createdAt: timestamp('created_at').defaultNow().notNull(),
		updatedAt: timestamp('updated_at')
			.$onUpdate(() => /* @__PURE__ */ new Date())
			.notNull(),
	},
	(table) => [index('account_userId_idx').on(table.userId)],
);

export const verification = pgTable(
	'verification',
	{
		id: text('id').primaryKey(),
		identifier: text('identifier').notNull(),
		value: text('value').notNull(),
		expiresAt: timestamp('expires_at').notNull(),
		createdAt: timestamp('created_at').defaultNow().notNull(),
		updatedAt: timestamp('updated_at')
			.defaultNow()
			.$onUpdate(() => /* @__PURE__ */ new Date())
			.notNull(),
	},
	(table) => [index('verification_identifier_idx').on(table.identifier)],
);

/**
 * Device authorization codes issued by BetterAuth's deviceAuthorization plugin.
 * Stores pending/approved/denied device login requests for kiosk/mobile clients.
 */
export const deviceCode = pgTable('device_code', {
	/** Primary key generated by the adapter */
	id: text('id')
		.primaryKey()
		.$defaultFn(() => randomUUID()),
	/** Opaque device verification code used by the polling client */
	deviceCode: text('device_code').notNull().unique(),
	/** Human-friendly code that the user types into the verification page */
	userCode: text('user_code').notNull().unique(),
	/** Authenticated user that approved the device */
	userId: text('user_id').references(() => user.id, { onDelete: 'set null' }),
	/** When the device code expires */
	expiresAt: timestamp('expires_at').notNull(),
	/** Current status of the authorization request */
	status: text('status').notNull().default('pending'),
	/** Last time the device polled for a token (for slow_down handling) */
	lastPolledAt: timestamp('last_polled_at'),
	/** Minimum polling interval in milliseconds */
	pollingInterval: integer('polling_interval'),
	/** OAuth client identifier that initiated the request */
	clientId: text('client_id'),
	/** Requested scopes (space-separated) */
	scope: text('scope'),
});

export const apikey = pgTable('apikey', {
	id: text('id').primaryKey(),
	name: text('name'),
	start: text('start'),
	prefix: text('prefix'),
	key: text('key').notNull(),
	userId: text('user_id')
		.notNull()
		.references(() => user.id, { onDelete: 'cascade' }),
	refillInterval: integer('refill_interval'),
	refillAmount: integer('refill_amount'),
	lastRefillAt: timestamp('last_refill_at'),
	enabled: boolean('enabled').default(true),
	rateLimitEnabled: boolean('rate_limit_enabled').default(true),
	rateLimitTimeWindow: integer('rate_limit_time_window').default(86400000),
	rateLimitMax: integer('rate_limit_max').default(10),
	requestCount: integer('request_count').default(0),
	remaining: integer('remaining'),
	lastRequest: timestamp('last_request'),
	expiresAt: timestamp('expires_at'),
	createdAt: timestamp('created_at').notNull(),
	updatedAt: timestamp('updated_at').notNull(),
	permissions: text('permissions'),
	metadata: text('metadata'),
});

// ============================================================================
// Organization Tables (Managed by BetterAuth Organization Plugin)
// ============================================================================

/**
 * Organization table - stores organization/tenant information.
 * Used by the better-auth organization plugin for multi-tenant support.
 */
export const organization = pgTable('organization', {
	id: text('id').primaryKey(),
	/** Organization display name */
	name: text('name').notNull(),
	/** URL-friendly unique identifier */
	slug: text('slug').notNull().unique(),
	/** Organization logo URL */
	logo: text('logo'),
	/** Additional metadata as JSON */
	metadata: text('metadata'),
	createdAt: timestamp('created_at').defaultNow().notNull(),
});

/**
 * Member table - stores organization membership.
 * Links users to organizations with roles.
 */
export const member = pgTable('member', {
	id: text('id').primaryKey(),
	/** Reference to the organization */
	organizationId: text('organization_id')
		.notNull()
		.references(() => organization.id, { onDelete: 'cascade' }),
	/** Reference to the user */
	userId: text('user_id')
		.notNull()
		.references(() => user.id, { onDelete: 'cascade' }),
	/** Member role within the organization (e.g., 'owner', 'admin', 'member') */
	role: text('role').default('member').notNull(),
	createdAt: timestamp('created_at').defaultNow().notNull(),
});

/**
 * Invitation table - stores pending organization invitations.
 * Allows inviting users to join organizations.
 */
export const invitation = pgTable('invitation', {
	id: text('id').primaryKey(),
	/** Reference to the organization */
	organizationId: text('organization_id')
		.notNull()
		.references(() => organization.id, { onDelete: 'cascade' }),
	/** Email address of the invited user */
	email: text('email').notNull(),
	/** Role to assign when invitation is accepted */
	role: text('role'),
	/** Current status: pending, accepted, rejected, canceled */
	status: text('status').default('pending').notNull(),
	/** When the invitation expires */
	expiresAt: timestamp('expires_at').notNull(),
	/** Reference to the user who sent the invitation */
	inviterId: text('inviter_id')
		.notNull()
		.references(() => user.id, { onDelete: 'cascade' }),
});

// ============================================================================
// Relations
// ============================================================================

export const userRelations = relations(user, ({ many }) => ({
	sessions: many(session),
	accounts: many(account),
	apikeys: many(apikey),
	members: many(member),
	invitations: many(invitation),
	deviceCodes: many(deviceCode),
}));

export const sessionRelations = relations(session, ({ one }) => ({
	user: one(user, {
		fields: [session.userId],
		references: [user.id],
	}),
}));

export const accountRelations = relations(account, ({ one }) => ({
	user: one(user, {
		fields: [account.userId],
		references: [user.id],
	}),
}));

export const apikeyRelations = relations(apikey, ({ one }) => ({
	user: one(user, {
		fields: [apikey.userId],
		references: [user.id],
	}),
}));

export const organizationRelations = relations(organization, ({ many }) => ({
	members: many(member),
	invitations: many(invitation),
}));

export const memberRelations = relations(member, ({ one }) => ({
	organization: one(organization, {
		fields: [member.organizationId],
		references: [organization.id],
	}),
	user: one(user, {
		fields: [member.userId],
		references: [user.id],
	}),
}));

export const invitationRelations = relations(invitation, ({ one }) => ({
	organization: one(organization, {
		fields: [invitation.organizationId],
		references: [organization.id],
	}),
	user: one(user, {
		fields: [invitation.inviterId],
		references: [user.id],
	}),
}));

export const deviceCodeRelations = relations(deviceCode, ({ one }) => ({
	user: one(user, {
		fields: [deviceCode.userId],
		references: [user.id],
	}),
}));

// ============================================================================
// Enums
// ============================================================================

/**
 * Enum for attendance record types
 */
export const attendanceType = pgEnum('attendance_type', [
	'CHECK_IN',
	'CHECK_OUT',
	'CHECK_OUT_AUTHORIZED',
]);

/**
 * Enum for employee status
 */
export const employeeStatus = pgEnum('employee_status', ['ACTIVE', 'INACTIVE', 'ON_LEAVE']);

/**
 * Enum for device status
 */
export const deviceStatus = pgEnum('device_status', ['ONLINE', 'OFFLINE', 'MAINTENANCE']);

/**
 * Enum for payment frequency
 */
export const paymentFrequency = pgEnum('payment_frequency', ['WEEKLY', 'BIWEEKLY', 'MONTHLY']);

/**
 * Enum for shift types per Mexican labor law (LFT Art. 60-61)
 */
export const shiftType = pgEnum('shift_type', ['DIURNA', 'NOCTURNA', 'MIXTA']);

/**
 * Enum for schedule exception types.
 */
export const scheduleExceptionType = pgEnum('schedule_exception_type', [
	'DAY_OFF',
	'MODIFIED',
	'EXTRA_DAY',
]);

/**
 * Enum for vacation request status.
 */
export const vacationRequestStatus = pgEnum('vacation_request_status', [
	'DRAFT',
	'SUBMITTED',
	'APPROVED',
	'REJECTED',
	'CANCELLED',
]);

/**
 * Enum for vacation request day type.
 */
export const vacationDayType = pgEnum('vacation_day_type', [
	'SCHEDULED_WORKDAY',
	'SCHEDULED_REST_DAY',
	'EXCEPTION_WORKDAY',
	'EXCEPTION_DAY_OFF',
	'MANDATORY_REST_DAY',
]);

/**
 * Enum for geographic zones (CONASAMI)
 */
export const geographicZone = pgEnum('geographic_zone', ['GENERAL', 'ZLFN']);

/**
 * Enum for overtime enforcement behavior
 */
export const overtimeEnforcement = pgEnum('overtime_enforcement', ['WARN', 'BLOCK']);

/**
 * Enum for payroll run status
 */
export const payrollRunStatus = pgEnum('payroll_run_status', ['DRAFT', 'PROCESSED']);

// ============================================================================
// Domain Tables
// ============================================================================

/**
 * @deprecated Client table - kept for legacy data only. New code should use `organization`.
 */
export const client = pgTable('client', {
	id: text('id').primaryKey(),
	name: text('name').notNull(),
	apiKeyId: text('api_key_id').references(() => apikey.id, { onDelete: 'set null' }),
	organizationId: text('organization_id').references(() => organization.id, {
		onDelete: 'set null',
	}),
	createdAt: timestamp('created_at').defaultNow().notNull(),
	updatedAt: timestamp('updated_at')
		.defaultNow()
		.$onUpdate(() => /* @__PURE__ */ new Date())
		.notNull(),
});

/**
 * Location table - stores location/branch information scoped to an organization.
 */
export const location = pgTable('location', {
	id: text('id').primaryKey(),
	name: text('name').notNull(),
	code: text('code').notNull().unique(),
	address: text('address'),
	/** Latitude coordinate (WGS84). */
	latitude: doublePrecision('latitude'),
	/** Longitude coordinate (WGS84). */
	longitude: doublePrecision('longitude'),
	/** Organization that owns the location (primary tenant foreign key) */
	organizationId: text('organization_id').references(() => organization.id, {
		onDelete: 'cascade',
	}),
	/** Geographic zone for minimum wage validation (CONASAMI) */
	geographicZone: geographicZone('geographic_zone').default('GENERAL').notNull(),
	/**
	 * IANA timezone identifier for this location (used for day boundaries in payroll).
	 *
	 * Examples: "America/Mexico_City", "America/Tijuana"
	 */
	timeZone: text('time_zone').default('America/Mexico_City').notNull(),
	/** @deprecated Legacy client reference. Use organizationId instead. */
	clientId: text('client_id').references(() => client.id, { onDelete: 'set null' }),
	createdAt: timestamp('created_at').defaultNow().notNull(),
	updatedAt: timestamp('updated_at')
		.defaultNow()
		.$onUpdate(() => /* @__PURE__ */ new Date())
		.notNull(),
});

/**
 * JobPosition table - stores job positions/roles for employees within an organization.
 */
export const jobPosition = pgTable('job_position', {
	id: text('id').primaryKey(),
	/** Position name (e.g., "Software Engineer", "Manager") */
	name: text('name').notNull(),
	/** Optional description of the position */
	description: text('description'),
	/** Organization this position belongs to (replaces legacy client linkage) */
	organizationId: text('organization_id').references(() => organization.id, {
		onDelete: 'cascade',
	}),
	/** @deprecated Legacy client reference. Use organizationId instead. */
	clientId: text('client_id').references(() => client.id, { onDelete: 'set null' }),
	createdAt: timestamp('created_at').defaultNow().notNull(),
	updatedAt: timestamp('updated_at')
		.defaultNow()
		.$onUpdate(() => /* @__PURE__ */ new Date())
		.notNull(),
});

/**
 * Schedule Template table - reusable weekly templates per organization.
 */
export const scheduleTemplate = pgTable('schedule_template', {
	id: text('id')
		.primaryKey()
		.$defaultFn(() => randomUUID()),
	name: text('name').notNull(),
	description: text('description'),
	shiftType: shiftType('shift_type').default('DIURNA').notNull(),
	organizationId: text('organization_id')
		.notNull()
		.references(() => organization.id, { onDelete: 'cascade' }),
	createdAt: timestamp('created_at').defaultNow().notNull(),
	updatedAt: timestamp('updated_at')
		.defaultNow()
		.$onUpdate(() => /* @__PURE__ */ new Date())
		.notNull(),
});

/**
 * Schedule Template Day table - daily configuration for templates.
 */
export const scheduleTemplateDay = pgTable(
	'schedule_template_day',
	{
		id: text('id')
			.primaryKey()
			.$defaultFn(() => randomUUID()),
		templateId: text('template_id')
			.notNull()
			.references(() => scheduleTemplate.id, { onDelete: 'cascade' }),
		dayOfWeek: integer('day_of_week').notNull(), // 0=Sunday, 6=Saturday
		startTime: time('start_time', { withTimezone: false }).notNull(),
		endTime: time('end_time', { withTimezone: false }).notNull(),
		isWorkingDay: boolean('is_working_day').default(true).notNull(),
		createdAt: timestamp('created_at').defaultNow().notNull(),
		updatedAt: timestamp('updated_at')
			.defaultNow()
			.$onUpdate(() => /* @__PURE__ */ new Date())
			.notNull(),
	},
	(table) => [
		index('schedule_template_day_template_idx').on(table.templateId),
		uniqueIndex('schedule_template_day_uniq').on(table.templateId, table.dayOfWeek),
	],
);

/**
 * Employee table - stores employee information
 */
export const employee = pgTable(
	'employee',
	{
		id: text('id').primaryKey(),
		/** Unique employee code/badge number */
		code: text('code').notNull().unique(),
		firstName: text('first_name').notNull(),
		lastName: text('last_name').notNull(),
		email: text('email'),
		/** Contact phone number */
		phone: text('phone'),
		/** Reference to employee's job position */
		jobPositionId: text('job_position_id').references(() => jobPosition.id, {
			onDelete: 'set null',
		}),
		/** Department name */
		department: text('department'),
		/** Employee status (ACTIVE, INACTIVE, ON_LEAVE) */
		status: employeeStatus('status').default('ACTIVE').notNull(),
		/** Employee shift type used for hour limits */
		shiftType: shiftType('shift_type').default('DIURNA').notNull(),
		/** Date when employee was hired */
		hireDate: timestamp('hire_date'),
		/** Daily pay rate for payroll calculations (salario diario) */
		dailyPay: numeric('daily_pay', { precision: 10, scale: 2 }).default('0').notNull(),
		/** Payment frequency for this employee */
		paymentFrequency: paymentFrequency('payment_frequency').default('MONTHLY').notNull(),
		/**
		 * Optional SBC daily override (Salario Base de Cotización diario).
		 * When provided, this value overrides the automatic SDI/SBC calculation.
		 */
		sbcDailyOverride: numeric('sbc_daily_override', { precision: 10, scale: 2 }),
		/** Location where employee works */
		locationId: text('location_id').references(() => location.id, { onDelete: 'set null' }),
		/** Assigned schedule template */
		scheduleTemplateId: text('schedule_template_id').references(() => scheduleTemplate.id, {
			onDelete: 'set null',
		}),
		/** Organization that the employee belongs to */
		organizationId: text('organization_id').references(() => organization.id, {
			onDelete: 'cascade',
		}),
		/** Linked BetterAuth user for self-service access */
		userId: text('user_id').references(() => user.id, { onDelete: 'set null' }),
		/**
		 * Last time payroll was processed for this employee.
		 * Set by payroll runs to avoid double-payment in a period.
		 */
		lastPayrollDate: timestamp('last_payroll_date'),
		/**
		 * Rekognition user ID for face recognition.
		 * Links the employee to their User Vector in the AWS Rekognition collection.
		 */
		rekognitionUserId: text('rekognition_user_id'),
		createdAt: timestamp('created_at').defaultNow().notNull(),
		updatedAt: timestamp('updated_at')
			.defaultNow()
			.$onUpdate(() => /* @__PURE__ */ new Date())
			.notNull(),
	},
	(table) => [uniqueIndex('employee_org_user_uniq').on(table.organizationId, table.userId)],
);

/**
 * Employee audit events - tracks changes to employee records.
 */
export const employeeAuditEvent = pgTable(
	'employee_audit_event',
	{
		id: text('id')
			.primaryKey()
			.$defaultFn(() => randomUUID()),
		employeeId: text('employee_id')
			.notNull()
			.references(() => employee.id, { onDelete: 'cascade' }),
		organizationId: text('organization_id').references(() => organization.id, {
			onDelete: 'cascade',
		}),
		action: text('action').notNull(),
		actorType: text('actor_type').notNull(),
		actorUserId: text('actor_user_id').references(() => user.id, { onDelete: 'set null' }),
		before: jsonb('before').$type<Record<string, unknown> | null>(),
		after: jsonb('after').$type<Record<string, unknown> | null>(),
		changedFields: jsonb('changed_fields').$type<string[]>().default([]).notNull(),
		createdAt: timestamp('created_at').defaultNow().notNull(),
	},
	(table) => [
		index('employee_audit_employee_idx').on(table.employeeId),
		index('employee_audit_org_idx').on(table.organizationId),
	],
);

/**
 * Device table - stores kiosk/device information
 */
export const device = pgTable('device', {
	id: text('id').primaryKey(),
	/** Unique device code */
	code: text('code').notNull().unique(),
	/** Device name/label */
	name: text('name'),
	/** Type of device (TABLET, KIOSK, MOBILE) */
	deviceType: text('device_type'),
	/** Device status (ONLINE, OFFLINE, MAINTENANCE) */
	status: deviceStatus('status').default('OFFLINE').notNull(),
	/** Last time device sent a heartbeat */
	lastHeartbeat: timestamp('last_heartbeat'),
	/** Location where device is installed */
	locationId: text('location_id').references(() => location.id, { onDelete: 'set null' }),
	/** Organization that owns the device */
	organizationId: text('organization_id').references(() => organization.id, {
		onDelete: 'cascade',
	}),
	createdAt: timestamp('created_at').defaultNow().notNull(),
	updatedAt: timestamp('updated_at')
		.defaultNow()
		.$onUpdate(() => /* @__PURE__ */ new Date())
		.notNull(),
});

/**
 * AttendanceRecord table - stores attendance check-in/check-out records
 */
export const attendanceRecord = pgTable('attendance_record', {
	id: text('id').primaryKey(),
	employeeId: text('employee_id')
		.notNull()
		.references(() => employee.id, { onDelete: 'cascade' }),
	deviceId: text('device_id')
		.notNull()
		.references(() => device.id, { onDelete: 'cascade' }),
	timestamp: timestamp('timestamp').notNull(),
	type: attendanceType('type').notNull(),
	/**
	 * Additional metadata for Rekognition integration
	 * Stores match score, raw payload, face recognition data, etc.
	 */
	metadata: jsonb('metadata'),
	createdAt: timestamp('created_at').defaultNow().notNull(),
	updatedAt: timestamp('updated_at')
		.defaultNow()
		.$onUpdate(() => /* @__PURE__ */ new Date())
		.notNull(),
});

/**
 * Employee schedule table - stores weekly schedules per employee.
 */
export const employeeSchedule = pgTable(
	'employee_schedule',
	{
		id: text('id')
			.primaryKey()
			.$defaultFn(() => randomUUID()),
		employeeId: text('employee_id')
			.notNull()
			.references(() => employee.id, { onDelete: 'cascade' }),
		dayOfWeek: integer('day_of_week').notNull(), // 0 = Sunday, 6 = Saturday
		startTime: time('start_time', { withTimezone: false }).notNull(),
		endTime: time('end_time', { withTimezone: false }).notNull(),
		isWorkingDay: boolean('is_working_day').default(true).notNull(),
		createdAt: timestamp('created_at').defaultNow().notNull(),
		updatedAt: timestamp('updated_at')
			.defaultNow()
			.$onUpdate(() => /* @__PURE__ */ new Date())
			.notNull(),
	},
	(table) => [
		index('employee_schedule_employee_idx').on(table.employeeId),
		uniqueIndex('employee_schedule_employee_day_uniq').on(table.employeeId, table.dayOfWeek),
	],
);

/**
 * Vacation request table - stores vacation requests per employee.
 */
export const vacationRequest = pgTable(
	'vacation_request',
	{
		id: text('id')
			.primaryKey()
			.$defaultFn(() => randomUUID()),
		organizationId: text('organization_id')
			.notNull()
			.references(() => organization.id, { onDelete: 'cascade' }),
		employeeId: text('employee_id')
			.notNull()
			.references(() => employee.id, { onDelete: 'cascade' }),
		requestedByUserId: text('requested_by_user_id').references(() => user.id, {
			onDelete: 'set null',
		}),
		status: vacationRequestStatus('status').default('SUBMITTED').notNull(),
		startDateKey: text('start_date_key').notNull(),
		endDateKey: text('end_date_key').notNull(),
		requestedNotes: text('requested_notes'),
		decisionNotes: text('decision_notes'),
		approvedByUserId: text('approved_by_user_id').references(() => user.id, {
			onDelete: 'set null',
		}),
		approvedAt: timestamp('approved_at'),
		rejectedByUserId: text('rejected_by_user_id').references(() => user.id, {
			onDelete: 'set null',
		}),
		rejectedAt: timestamp('rejected_at'),
		cancelledByUserId: text('cancelled_by_user_id').references(() => user.id, {
			onDelete: 'set null',
		}),
		cancelledAt: timestamp('cancelled_at'),
		createdAt: timestamp('created_at').defaultNow().notNull(),
		updatedAt: timestamp('updated_at')
			.defaultNow()
			.$onUpdate(() => /* @__PURE__ */ new Date())
			.notNull(),
	},
	(table) => [
		index('vacation_request_org_status_idx').on(table.organizationId, table.status),
		index('vacation_request_employee_idx').on(table.employeeId),
		index('vacation_request_org_start_idx').on(table.organizationId, table.startDateKey),
		index('vacation_request_org_end_idx').on(table.organizationId, table.endDateKey),
	],
);

/**
 * Vacation request day table - stores per-day breakdown for requests.
 */
export const vacationRequestDay = pgTable(
	'vacation_request_day',
	{
		id: text('id')
			.primaryKey()
			.$defaultFn(() => randomUUID()),
		requestId: text('request_id')
			.notNull()
			.references(() => vacationRequest.id, { onDelete: 'cascade' }),
		employeeId: text('employee_id')
			.notNull()
			.references(() => employee.id, { onDelete: 'cascade' }),
		dateKey: text('date_key').notNull(),
		countsAsVacationDay: boolean('counts_as_vacation_day').default(false).notNull(),
		dayType: vacationDayType('day_type').notNull(),
		serviceYearNumber: integer('service_year_number'),
		createdAt: timestamp('created_at').defaultNow().notNull(),
	},
	(table) => [
		uniqueIndex('vacation_request_day_request_date_uniq').on(table.requestId, table.dateKey),
		index('vacation_request_day_employee_date_idx').on(table.employeeId, table.dateKey),
	],
);

/**
 * Schedule Exception table - date-specific overrides for employee schedules.
 */
export const scheduleException = pgTable(
	'schedule_exception',
	{
		id: text('id')
			.primaryKey()
			.$defaultFn(() => randomUUID()),
		employeeId: text('employee_id')
			.notNull()
			.references(() => employee.id, { onDelete: 'cascade' }),
		exceptionDate: timestamp('exception_date').notNull(),
		exceptionType: scheduleExceptionType('exception_type').notNull(),
		startTime: time('start_time', { withTimezone: false }),
		endTime: time('end_time', { withTimezone: false }),
		reason: text('reason'),
		vacationRequestId: text('vacation_request_id').references(() => vacationRequest.id, {
			onDelete: 'set null',
		}),
		createdAt: timestamp('created_at').defaultNow().notNull(),
		updatedAt: timestamp('updated_at')
			.defaultNow()
			.$onUpdate(() => /* @__PURE__ */ new Date())
			.notNull(),
	},
	(table) => [
		index('schedule_exception_employee_idx').on(table.employeeId),
		index('schedule_exception_date_idx').on(table.exceptionDate),
		uniqueIndex('schedule_exception_employee_date_uniq').on(
			table.employeeId,
			table.exceptionDate,
		),
	],
);

/**
 * Payroll settings per organization.
 */
export const payrollSetting = pgTable('payroll_setting', {
	id: text('id')
		.primaryKey()
		.$defaultFn(() => randomUUID()),
	organizationId: text('organization_id')
		.notNull()
		.unique()
		.references(() => organization.id, { onDelete: 'cascade' }),
	/**
	 * IANA timezone identifier for payroll periods (used for start/end boundaries).
	 *
	 * Examples: "America/Mexico_City", "America/Tijuana"
	 */
	timeZone: text('time_zone').default('America/Mexico_City').notNull(),
	weekStartDay: integer('week_start_day').default(1).notNull(), // default Monday
	/** Behavior when overtime limits are exceeded */
	overtimeEnforcement: overtimeEnforcement('overtime_enforcement').default('WARN').notNull(),
	/**
	 * Additional mandatory rest days (YYYY-MM-DD) configured per organization.
	 *
	 * Used primarily for Art. 74 fr. IX ("jornada electoral") and other local/organizational
	 * rest days that are date-specific.
	 */
	additionalMandatoryRestDays: jsonb('additional_mandatory_rest_days')
		.$type<string[]>()
		.default([])
		.notNull(),
	/** Risk of work rate (prima de riesgo de trabajo) */
	riskWorkRate: numeric('risk_work_rate', { precision: 6, scale: 4 }).default('0').notNull(),
	/** State payroll tax rate (ISN) */
	statePayrollTaxRate: numeric('state_payroll_tax_rate', { precision: 6, scale: 4 })
		.default('0')
		.notNull(),
	/** Whether the employer absorbs the employee IMSS share */
	absorbImssEmployeeShare: boolean('absorb_imss_employee_share').default(false).notNull(),
	/** Whether the employer absorbs ISR withholding */
	absorbIsr: boolean('absorb_isr').default(false).notNull(),
	/** Aguinaldo days for SDI/SBC integration factor */
	aguinaldoDays: integer('aguinaldo_days').default(15).notNull(),
	/** Vacation premium rate for SDI/SBC integration factor */
	vacationPremiumRate: numeric('vacation_premium_rate', { precision: 6, scale: 4 })
		.default('0.25')
		.notNull(),
	/** Enables the seventh day pay calculation */
	enableSeventhDayPay: boolean('enable_seventh_day_pay').default(false).notNull(),
	createdAt: timestamp('created_at').defaultNow().notNull(),
	updatedAt: timestamp('updated_at')
		.defaultNow()
		.$onUpdate(() => /* @__PURE__ */ new Date())
		.notNull(),
});

// ============================================================================
// Relations - Scheduling
// ============================================================================

export const scheduleTemplateRelations = relations(scheduleTemplate, ({ one, many }) => ({
	organization: one(organization, {
		fields: [scheduleTemplate.organizationId],
		references: [organization.id],
	}),
	days: many(scheduleTemplateDay),
	employees: many(employee),
}));

export const scheduleTemplateDayRelations = relations(scheduleTemplateDay, ({ one }) => ({
	template: one(scheduleTemplate, {
		fields: [scheduleTemplateDay.templateId],
		references: [scheduleTemplate.id],
	}),
}));

export const employeeRelations = relations(employee, ({ one, many }) => ({
	jobPosition: one(jobPosition, {
		fields: [employee.jobPositionId],
		references: [jobPosition.id],
	}),
	location: one(location, {
		fields: [employee.locationId],
		references: [location.id],
	}),
	organization: one(organization, {
		fields: [employee.organizationId],
		references: [organization.id],
	}),
	scheduleTemplate: one(scheduleTemplate, {
		fields: [employee.scheduleTemplateId],
		references: [scheduleTemplate.id],
	}),
	user: one(user, {
		fields: [employee.userId],
		references: [user.id],
	}),
	scheduleEntries: many(employeeSchedule),
	scheduleExceptions: many(scheduleException),
	vacationRequests: many(vacationRequest),
	vacationRequestDays: many(vacationRequestDay),
	auditEvents: many(employeeAuditEvent),
}));

export const employeeAuditEventRelations = relations(employeeAuditEvent, ({ one }) => ({
	employee: one(employee, {
		fields: [employeeAuditEvent.employeeId],
		references: [employee.id],
	}),
	organization: one(organization, {
		fields: [employeeAuditEvent.organizationId],
		references: [organization.id],
	}),
	actor: one(user, {
		fields: [employeeAuditEvent.actorUserId],
		references: [user.id],
	}),
}));

export const scheduleExceptionRelations = relations(scheduleException, ({ one }) => ({
	employee: one(employee, {
		fields: [scheduleException.employeeId],
		references: [employee.id],
	}),
	vacationRequest: one(vacationRequest, {
		fields: [scheduleException.vacationRequestId],
		references: [vacationRequest.id],
	}),
}));

export const vacationRequestRelations = relations(vacationRequest, ({ one, many }) => ({
	organization: one(organization, {
		fields: [vacationRequest.organizationId],
		references: [organization.id],
	}),
	employee: one(employee, {
		fields: [vacationRequest.employeeId],
		references: [employee.id],
	}),
	days: many(vacationRequestDay),
}));

export const vacationRequestDayRelations = relations(vacationRequestDay, ({ one }) => ({
	request: one(vacationRequest, {
		fields: [vacationRequestDay.requestId],
		references: [vacationRequest.id],
	}),
	employee: one(employee, {
		fields: [vacationRequestDay.employeeId],
		references: [employee.id],
	}),
}));

/**
 * Payroll run header table.
 */
export const payrollRun = pgTable('payroll_run', {
	id: text('id')
		.primaryKey()
		.$defaultFn(() => randomUUID()),
	organizationId: text('organization_id')
		.notNull()
		.references(() => organization.id, { onDelete: 'cascade' }),
	periodStart: timestamp('period_start').notNull(),
	periodEnd: timestamp('period_end').notNull(),
	paymentFrequency: paymentFrequency('payment_frequency').notNull(),
	status: payrollRunStatus('status').default('DRAFT').notNull(),
	totalAmount: numeric('total_amount', { precision: 12, scale: 2 }).default('0').notNull(),
	employeeCount: integer('employee_count').default(0).notNull(),
	/** Snapshot of fiscal totals for the run */
	taxSummary: jsonb('tax_summary').$type<Record<string, unknown>>(),
	processedAt: timestamp('processed_at'),
	createdAt: timestamp('created_at').defaultNow().notNull(),
	updatedAt: timestamp('updated_at')
		.defaultNow()
		.$onUpdate(() => /* @__PURE__ */ new Date())
		.notNull(),
});

/**
 * Payroll run line items per employee.
 */
export const payrollRunEmployee = pgTable('payroll_run_employee', {
	id: text('id')
		.primaryKey()
		.$defaultFn(() => randomUUID()),
	payrollRunId: text('payroll_run_id')
		.notNull()
		.references(() => payrollRun.id, { onDelete: 'cascade' }),
	employeeId: text('employee_id')
		.notNull()
		.references(() => employee.id, { onDelete: 'cascade' }),
	hoursWorked: numeric('hours_worked', { precision: 10, scale: 2 }).default('0').notNull(),
	hourlyPay: numeric('hourly_pay', { precision: 10, scale: 2 }).default('0').notNull(),
	totalPay: numeric('total_pay', { precision: 12, scale: 2 }).default('0').notNull(),
	normalHours: numeric('normal_hours', { precision: 10, scale: 2 }).default('0').notNull(),
	normalPay: numeric('normal_pay', { precision: 12, scale: 2 }).default('0').notNull(),
	overtimeDoubleHours: numeric('overtime_double_hours', { precision: 10, scale: 2 })
		.default('0')
		.notNull(),
	overtimeDoublePay: numeric('overtime_double_pay', { precision: 12, scale: 2 })
		.default('0')
		.notNull(),
	overtimeTripleHours: numeric('overtime_triple_hours', { precision: 10, scale: 2 })
		.default('0')
		.notNull(),
	overtimeTriplePay: numeric('overtime_triple_pay', { precision: 12, scale: 2 })
		.default('0')
		.notNull(),
	sundayPremiumAmount: numeric('sunday_premium_amount', { precision: 12, scale: 2 })
		.default('0')
		.notNull(),
	mandatoryRestDayPremiumAmount: numeric('mandatory_rest_day_premium_amount', {
		precision: 12,
		scale: 2,
	})
		.default('0')
		.notNull(),
	vacationDaysPaid: integer('vacation_days_paid').default(0).notNull(),
	vacationPayAmount: numeric('vacation_pay_amount', { precision: 12, scale: 2 })
		.default('0')
		.notNull(),
	vacationPremiumAmount: numeric('vacation_premium_amount', { precision: 12, scale: 2 })
		.default('0')
		.notNull(),
	/** Snapshot of fiscal breakdown for the employee line */
	taxBreakdown: jsonb('tax_breakdown').$type<Record<string, unknown>>(),
	periodStart: timestamp('period_start').notNull(),
	periodEnd: timestamp('period_end').notNull(),
	createdAt: timestamp('created_at').defaultNow().notNull(),
	updatedAt: timestamp('updated_at')
		.defaultNow()
		.$onUpdate(() => /* @__PURE__ */ new Date())
		.notNull(),
});
