import { relations } from 'drizzle-orm';
import {
	boolean,
	doublePrecision,
	index,
	integer,
	jsonb,
	numeric,
	pgEnum,
	pgTable,
	text,
	time,
	timestamp,
	uniqueIndex,
} from 'drizzle-orm/pg-core';
import { randomUUID } from 'node:crypto';
import type { EmployeeTerminationSettlement } from '@sen-checkin/types';

// ============================================================================
// Auth Tables (Managed by BetterAuth)
// ============================================================================

/**
 * User table - stores user account information.
 * Extended with admin plugin fields for role management and banning.
 */
export const user = pgTable('user', {
	id: text('id').primaryKey(),
	name: text('name').notNull(),
	email: text('email').notNull().unique(),
	emailVerified: boolean('email_verified').default(false).notNull(),
	image: text('image'),
	createdAt: timestamp('created_at').defaultNow().notNull(),
	updatedAt: timestamp('updated_at')
		.defaultNow()
		.$onUpdate(() => /* @__PURE__ */ new Date())
		.notNull(),
	/** User role for admin plugin (e.g., 'user', 'admin') */
	role: text('role').default('user'),
	/** Whether the user is banned from the system */
	banned: boolean('banned').default(false),
	/** Reason for banning the user */
	banReason: text('ban_reason'),
	/** When the ban expires (null = permanent) */
	banExpires: timestamp('ban_expires'),
	/** Unique username for the user */
	username: text('username').unique(),
	/** Display username (can differ from username) */
	displayUsername: text('display_username'),
});

/**
 * Session table - stores user session information.
 * Extended with admin and organization plugin fields.
 */
export const session = pgTable(
	'session',
	{
		id: text('id').primaryKey(),
		expiresAt: timestamp('expires_at').notNull(),
		token: text('token').notNull().unique(),
		createdAt: timestamp('created_at').defaultNow().notNull(),
		updatedAt: timestamp('updated_at')
			.$onUpdate(() => /* @__PURE__ */ new Date())
			.notNull(),
		ipAddress: text('ip_address'),
		userAgent: text('user_agent'),
		userId: text('user_id')
			.notNull()
			.references(() => user.id, { onDelete: 'cascade' }),
		/** Admin user ID if this session is impersonating another user */
		impersonatedBy: text('impersonated_by'),
		/** Currently active organization ID for organization plugin */
		activeOrganizationId: text('active_organization_id'),
	},
	(table) => [index('session_userId_idx').on(table.userId)],
);

export const account = pgTable(
	'account',
	{
		id: text('id').primaryKey(),
		accountId: text('account_id').notNull(),
		providerId: text('provider_id').notNull(),
		userId: text('user_id')
			.notNull()
			.references(() => user.id, { onDelete: 'cascade' }),
		accessToken: text('access_token'),
		refreshToken: text('refresh_token'),
		idToken: text('id_token'),
		accessTokenExpiresAt: timestamp('access_token_expires_at'),
		refreshTokenExpiresAt: timestamp('refresh_token_expires_at'),
		scope: text('scope'),
		password: text('password'),
		createdAt: timestamp('created_at').defaultNow().notNull(),
		updatedAt: timestamp('updated_at')
			.$onUpdate(() => /* @__PURE__ */ new Date())
			.notNull(),
	},
	(table) => [index('account_userId_idx').on(table.userId)],
);

export const verification = pgTable(
	'verification',
	{
		id: text('id').primaryKey(),
		identifier: text('identifier').notNull(),
		value: text('value').notNull(),
		expiresAt: timestamp('expires_at').notNull(),
		createdAt: timestamp('created_at').defaultNow().notNull(),
		updatedAt: timestamp('updated_at')
			.defaultNow()
			.$onUpdate(() => /* @__PURE__ */ new Date())
			.notNull(),
	},
	(table) => [index('verification_identifier_idx').on(table.identifier)],
);

/**
 * Device authorization codes issued by BetterAuth's deviceAuthorization plugin.
 * Stores pending/approved/denied device login requests for kiosk/mobile clients.
 */
export const deviceCode = pgTable('device_code', {
	/** Primary key generated by the adapter */
	id: text('id')
		.primaryKey()
		.$defaultFn(() => randomUUID()),
	/** Opaque device verification code used by the polling client */
	deviceCode: text('device_code').notNull().unique(),
	/** Human-friendly code that the user types into the verification page */
	userCode: text('user_code').notNull().unique(),
	/** Authenticated user that approved the device */
	userId: text('user_id').references(() => user.id, { onDelete: 'set null' }),
	/** When the device code expires */
	expiresAt: timestamp('expires_at').notNull(),
	/** Current status of the authorization request */
	status: text('status').notNull().default('pending'),
	/** Last time the device polled for a token (for slow_down handling) */
	lastPolledAt: timestamp('last_polled_at'),
	/** Minimum polling interval in milliseconds */
	pollingInterval: integer('polling_interval'),
	/** OAuth client identifier that initiated the request */
	clientId: text('client_id'),
	/** Requested scopes (space-separated) */
	scope: text('scope'),
});

export const apikey = pgTable('apikey', {
	id: text('id').primaryKey(),
	name: text('name'),
	start: text('start'),
	prefix: text('prefix'),
	key: text('key').notNull(),
	userId: text('user_id')
		.notNull()
		.references(() => user.id, { onDelete: 'cascade' }),
	refillInterval: integer('refill_interval'),
	refillAmount: integer('refill_amount'),
	lastRefillAt: timestamp('last_refill_at'),
	enabled: boolean('enabled').default(true),
	rateLimitEnabled: boolean('rate_limit_enabled').default(true),
	rateLimitTimeWindow: integer('rate_limit_time_window').default(86400000),
	rateLimitMax: integer('rate_limit_max').default(10),
	requestCount: integer('request_count').default(0),
	remaining: integer('remaining'),
	lastRequest: timestamp('last_request'),
	expiresAt: timestamp('expires_at'),
	createdAt: timestamp('created_at').notNull(),
	updatedAt: timestamp('updated_at').notNull(),
	permissions: text('permissions'),
	metadata: text('metadata'),
});

// ============================================================================
// Organization Tables (Managed by BetterAuth Organization Plugin)
// ============================================================================

/**
 * Organization table - stores organization/tenant information.
 * Used by the better-auth organization plugin for multi-tenant support.
 */
export const organization = pgTable('organization', {
	id: text('id').primaryKey(),
	/** Organization display name */
	name: text('name').notNull(),
	/** URL-friendly unique identifier */
	slug: text('slug').notNull().unique(),
	/** Organization logo URL */
	logo: text('logo'),
	/** Additional metadata as JSON */
	metadata: text('metadata'),
	createdAt: timestamp('created_at').defaultNow().notNull(),
});

/**
 * Member table - stores organization membership.
 * Links users to organizations with roles.
 */
export const member = pgTable('member', {
	id: text('id').primaryKey(),
	/** Reference to the organization */
	organizationId: text('organization_id')
		.notNull()
		.references(() => organization.id, { onDelete: 'cascade' }),
	/** Reference to the user */
	userId: text('user_id')
		.notNull()
		.references(() => user.id, { onDelete: 'cascade' }),
	/** Member role within the organization (e.g., 'owner', 'admin', 'member') */
	role: text('role').default('member').notNull(),
	createdAt: timestamp('created_at').defaultNow().notNull(),
});

/**
 * Invitation table - stores pending organization invitations.
 * Allows inviting users to join organizations.
 */
export const invitation = pgTable('invitation', {
	id: text('id').primaryKey(),
	/** Reference to the organization */
	organizationId: text('organization_id')
		.notNull()
		.references(() => organization.id, { onDelete: 'cascade' }),
	/** Email address of the invited user */
	email: text('email').notNull(),
	/** Role to assign when invitation is accepted */
	role: text('role'),
	/** Current status: pending, accepted, rejected, canceled */
	status: text('status').default('pending').notNull(),
	/** When the invitation expires */
	expiresAt: timestamp('expires_at').notNull(),
	/** Reference to the user who sent the invitation */
	inviterId: text('inviter_id')
		.notNull()
		.references(() => user.id, { onDelete: 'cascade' }),
});

// ============================================================================
// Relations
// ============================================================================

export const userRelations = relations(user, ({ many }) => ({
	sessions: many(session),
	accounts: many(account),
	apikeys: many(apikey),
	members: many(member),
	invitations: many(invitation),
	deviceCodes: many(deviceCode),
	overtimeAuthorizationsApproved: many(overtimeAuthorization, {
		relationName: 'overtimeAuthorizationApprovedBy',
	}),
	disciplinaryMeasuresClosed: many(employeeDisciplinaryMeasure, {
		relationName: 'disciplinaryMeasureClosedBy',
	}),
	disciplinaryMeasuresCreated: many(employeeDisciplinaryMeasure, {
		relationName: 'disciplinaryMeasureCreatedBy',
	}),
	disciplinaryMeasuresUpdated: many(employeeDisciplinaryMeasure, {
		relationName: 'disciplinaryMeasureUpdatedBy',
	}),
	disciplinaryDocumentsUploaded: many(employeeDisciplinaryDocumentVersion),
	disciplinaryAttachmentsUploaded: many(employeeDisciplinaryAttachment),
	terminationDraftsCreated: many(employeeTerminationDraft, {
		relationName: 'terminationDraftCreatedBy',
	}),
	terminationDraftsUpdated: many(employeeTerminationDraft, {
		relationName: 'terminationDraftUpdatedBy',
	}),
}));

export const sessionRelations = relations(session, ({ one }) => ({
	user: one(user, {
		fields: [session.userId],
		references: [user.id],
	}),
}));

export const accountRelations = relations(account, ({ one }) => ({
	user: one(user, {
		fields: [account.userId],
		references: [user.id],
	}),
}));

export const apikeyRelations = relations(apikey, ({ one }) => ({
	user: one(user, {
		fields: [apikey.userId],
		references: [user.id],
	}),
}));

export const organizationRelations = relations(organization, ({ many }) => ({
	members: many(member),
	invitations: many(invitation),
	overtimeAuthorizations: many(overtimeAuthorization),
	terminationSettlements: many(employeeTerminationSettlement),
	documentWorkflowConfigs: many(organizationDocumentWorkflowConfig),
	documentRequirements: many(organizationDocumentRequirement),
	legalBrandings: many(organizationLegalBranding),
	legalTemplates: many(organizationLegalTemplate),
	legalGenerations: many(employeeLegalGeneration),
	documentVersions: many(employeeDocumentVersion),
	disciplinaryFolioCounters: many(organizationDisciplinaryFolioCounter),
	disciplinaryMeasures: many(employeeDisciplinaryMeasure),
	disciplinaryDocumentVersions: many(employeeDisciplinaryDocumentVersion),
	disciplinaryAttachments: many(employeeDisciplinaryAttachment),
	terminationDrafts: many(employeeTerminationDraft),
}));

export const memberRelations = relations(member, ({ one }) => ({
	organization: one(organization, {
		fields: [member.organizationId],
		references: [organization.id],
	}),
	user: one(user, {
		fields: [member.userId],
		references: [user.id],
	}),
}));

export const invitationRelations = relations(invitation, ({ one }) => ({
	organization: one(organization, {
		fields: [invitation.organizationId],
		references: [organization.id],
	}),
	user: one(user, {
		fields: [invitation.inviterId],
		references: [user.id],
	}),
}));

export const deviceCodeRelations = relations(deviceCode, ({ one }) => ({
	user: one(user, {
		fields: [deviceCode.userId],
		references: [user.id],
	}),
}));

// ============================================================================
// Enums
// ============================================================================

/**
 * Enum for attendance record types
 */
export const attendanceType = pgEnum('attendance_type', [
	'CHECK_IN',
	'CHECK_OUT',
	'CHECK_OUT_AUTHORIZED',
	'WORK_OFFSITE',
]);

/**
 * Enum for RH offsite-day classification.
 */
export const offsiteDayKind = pgEnum('offsite_day_kind', ['LABORABLE', 'NO_LABORABLE']);

/**
 * Enum for employee status
 */
export const employeeStatus = pgEnum('employee_status', ['ACTIVE', 'INACTIVE', 'ON_LEAVE']);

/**
 * Enum for employee termination reasons.
 */
export const terminationReason = pgEnum('termination_reason', [
	'voluntary_resignation',
	'justified_rescission',
	'unjustified_dismissal',
	'end_of_contract',
	'mutual_agreement',
	'death',
]);

/**
 * Enum for employment contract types.
 */
export const employmentContractType = pgEnum('employment_contract_type', [
	'indefinite',
	'fixed_term',
	'specific_work',
]);

/**
 * Enum for device status
 */
export const deviceStatus = pgEnum('device_status', ['ONLINE', 'OFFLINE', 'MAINTENANCE']);

/**
 * Enum for payment frequency
 */
export const paymentFrequency = pgEnum('payment_frequency', ['WEEKLY', 'BIWEEKLY', 'MONTHLY']);

/**
 * Enum for shift types per Mexican labor law (LFT Art. 60-61)
 */
export const shiftType = pgEnum('shift_type', ['DIURNA', 'NOCTURNA', 'MIXTA']);

/**
 * Enum for employment types (permanent vs eventual).
 */
export const employmentType = pgEnum('employment_type', ['PERMANENT', 'EVENTUAL']);

/**
 * Enum for PTU eligibility overrides.
 */
export const ptuEligibilityOverride = pgEnum('ptu_eligibility_override', [
	'DEFAULT',
	'INCLUDE',
	'EXCLUDE',
]);

/**
 * Enum for PTU mode behavior.
 */
export const ptuMode = pgEnum('ptu_mode', ['DEFAULT_RULES', 'MANUAL']);

/**
 * Enum for employer type (persona moral/física).
 */
export const employerType = pgEnum('employer_type', ['PERSONA_MORAL', 'PERSONA_FISICA']);

/**
 * Enum for schedule exception types.
 */
export const scheduleExceptionType = pgEnum('schedule_exception_type', [
	'DAY_OFF',
	'MODIFIED',
	'EXTRA_DAY',
]);

/**
 * Enum for vacation request status.
 */
export const vacationRequestStatus = pgEnum('vacation_request_status', [
	'DRAFT',
	'SUBMITTED',
	'APPROVED',
	'REJECTED',
	'CANCELLED',
]);

/**
 * Enum for vacation request day type.
 */
export const vacationDayType = pgEnum('vacation_day_type', [
	'SCHEDULED_WORKDAY',
	'SCHEDULED_REST_DAY',
	'EXCEPTION_WORKDAY',
	'EXCEPTION_DAY_OFF',
	'MANDATORY_REST_DAY',
	'INCAPACITY',
]);

/**
 * Enum for IMSS incapacity types.
 */
export const incapacityType = pgEnum('incapacity_type', ['EG', 'RT', 'MAT', 'LIC140BIS']);

/**
 * Enum for SAT incapacity types.
 */
export const satTipoIncapacidad = pgEnum('sat_tipo_incapacidad', ['01', '02', '03', '04']);

/**
 * Enum for incapacity issuance.
 */
export const incapacityIssuedBy = pgEnum('incapacity_issued_by', ['IMSS', 'recognized_by_IMSS']);

/**
 * Enum for incapacity sequences.
 */
export const incapacitySequence = pgEnum('incapacity_sequence', [
	'inicial',
	'subsecuente',
	'recaida',
]);

/**
 * Enum for incapacity record status.
 */
export const incapacityStatus = pgEnum('incapacity_status', ['ACTIVE', 'CANCELLED']);

/**
 * Enum for geographic zones (CONASAMI)
 */
export const geographicZone = pgEnum('geographic_zone', ['GENERAL', 'ZLFN']);

/**
 * Enum for overtime enforcement behavior
 */
export const overtimeEnforcement = pgEnum('overtime_enforcement', ['WARN', 'BLOCK']);

/**
 * Enum for overtime authorization status.
 */
export const overtimeAuthorizationStatus = pgEnum('overtime_authorization_status', [
	'PENDING',
	'ACTIVE',
	'CANCELLED',
]);

/**
 * Enum for payroll run status
 */
export const payrollRunStatus = pgEnum('payroll_run_status', ['DRAFT', 'PROCESSED']);

/**
 * Enum for holiday source.
 */
export const holidaySource = pgEnum('holiday_source', ['INTERNAL', 'PROVIDER', 'CUSTOM']);

/**
 * Enum for holiday review status.
 */
export const holidayStatus = pgEnum('holiday_status', [
	'PENDING_APPROVAL',
	'APPROVED',
	'REJECTED',
	'DEACTIVATED',
]);

/**
 * Enum for holiday kind.
 */
export const holidayKind = pgEnum('holiday_kind', ['MANDATORY', 'OPTIONAL']);

/**
 * Enum for holiday sync run status.
 */
export const holidaySyncRunStatus = pgEnum('holiday_sync_run_status', [
	'RUNNING',
	'COMPLETED',
	'FAILED',
]);

/**
 * Enum for PTU run status.
 */
export const ptuRunStatus = pgEnum('ptu_run_status', ['DRAFT', 'PROCESSED', 'CANCELLED']);

/**
 * Enum for aguinaldo run status.
 */
export const aguinaldoRunStatus = pgEnum('aguinaldo_run_status', [
	'DRAFT',
	'PROCESSED',
	'CANCELLED',
]);

/**
 * Enum for employee document requirement keys.
 */
export const employeeDocumentRequirementKey = pgEnum('employee_document_requirement_key', [
	'IDENTIFICATION',
	'TAX_CONSTANCY',
	'PROOF_OF_ADDRESS',
	'SOCIAL_SECURITY_EVIDENCE',
	'EMPLOYMENT_PROFILE',
	'SIGNED_CONTRACT',
	'SIGNED_NDA',
]);

/**
 * Enum for employee document review statuses.
 */
export const employeeDocumentReviewStatus = pgEnum('employee_document_review_status', [
	'PENDING_REVIEW',
	'APPROVED',
	'REJECTED',
]);

/**
 * Enum for employee document source values.
 */
export const employeeDocumentSource = pgEnum('employee_document_source', [
	'UPLOAD',
	'PHYSICAL_SIGNED_UPLOAD',
	'DIGITAL_SIGNATURE',
]);

/**
 * Enum for identification document subtype values.
 */
export const identificationSubtype = pgEnum('identification_subtype', ['INE', 'PASSPORT', 'OTHER']);

/**
 * Enum for employment profile subtype values.
 */
export const employmentProfileSubtype = pgEnum('employment_profile_subtype', [
	'CURRICULUM',
	'JOB_APPLICATION',
]);

/**
 * Enum for legal document kind.
 */
export const legalDocumentKind = pgEnum('legal_document_kind', [
	'CONTRACT',
	'NDA',
	'ACTA_ADMINISTRATIVA',
	'CONSTANCIA_NEGATIVA_FIRMA',
]);

/**
 * Enum for legal template status values.
 */
export const legalTemplateStatus = pgEnum('legal_template_status', ['DRAFT', 'PUBLISHED']);

/**
 * Enum for disciplinary measure status values.
 */
export const disciplinaryMeasureStatus = pgEnum('disciplinary_measure_status', [
	'DRAFT',
	'GENERATED',
	'CLOSED',
]);

/**
 * Enum for disciplinary outcomes.
 */
export const disciplinaryOutcome = pgEnum('disciplinary_outcome', [
	'no_action',
	'warning',
	'suspension',
	'termination_process',
]);

/**
 * Enum for disciplinary signature status values.
 */
export const disciplinarySignatureStatus = pgEnum('disciplinary_signature_status', [
	'signed_physical',
	'refused_to_sign',
]);

/**
 * Enum for disciplinary document kinds.
 */
export const disciplinaryDocumentKind = pgEnum('disciplinary_document_kind', [
	'ACTA_ADMINISTRATIVA',
	'CONSTANCIA_NEGATIVA_FIRMA',
]);

/**
 * Enum for disciplinary termination draft status values.
 */
export const terminationDraftStatus = pgEnum('termination_draft_status', [
	'ACTIVE',
	'CANCELLED',
	'CONSUMED',
]);

/**
 * Enum for document requirement activation stage.
 */
export const documentRequirementActivationStage = pgEnum('document_requirement_activation_stage', [
	'BASE',
	'LEGAL_AFTER_GATE',
]);

// ============================================================================
// Domain Tables
// ============================================================================

/**
 * @deprecated Client table - kept for legacy data only. New code should use `organization`.
 */
export const client = pgTable('client', {
	id: text('id').primaryKey(),
	name: text('name').notNull(),
	apiKeyId: text('api_key_id').references(() => apikey.id, { onDelete: 'set null' }),
	organizationId: text('organization_id').references(() => organization.id, {
		onDelete: 'set null',
	}),
	createdAt: timestamp('created_at').defaultNow().notNull(),
	updatedAt: timestamp('updated_at')
		.defaultNow()
		.$onUpdate(() => /* @__PURE__ */ new Date())
		.notNull(),
});

/**
 * Location table - stores location/branch information scoped to an organization.
 */
export const location = pgTable('location', {
	id: text('id').primaryKey(),
	name: text('name').notNull(),
	code: text('code').notNull().unique(),
	address: text('address'),
	/** Latitude coordinate (WGS84). */
	latitude: doublePrecision('latitude'),
	/** Longitude coordinate (WGS84). */
	longitude: doublePrecision('longitude'),
	/** Organization that owns the location (primary tenant foreign key) */
	organizationId: text('organization_id').references(() => organization.id, {
		onDelete: 'cascade',
	}),
	/** Geographic zone for minimum wage validation (CONASAMI) */
	geographicZone: geographicZone('geographic_zone').default('GENERAL').notNull(),
	/**
	 * IANA timezone identifier for this location (used for day boundaries in payroll).
	 *
	 * Examples: "America/Mexico_City", "America/Tijuana"
	 */
	timeZone: text('time_zone').default('America/Mexico_City').notNull(),
	/** @deprecated Legacy client reference. Use organizationId instead. */
	clientId: text('client_id').references(() => client.id, { onDelete: 'set null' }),
	createdAt: timestamp('created_at').defaultNow().notNull(),
	updatedAt: timestamp('updated_at')
		.defaultNow()
		.$onUpdate(() => /* @__PURE__ */ new Date())
		.notNull(),
});

/**
 * JobPosition table - stores job positions/roles for employees within an organization.
 */
export const jobPosition = pgTable('job_position', {
	id: text('id').primaryKey(),
	/** Position name (e.g., "Software Engineer", "Manager") */
	name: text('name').notNull(),
	/** Optional description of the position */
	description: text('description'),
	/** Organization this position belongs to (replaces legacy client linkage) */
	organizationId: text('organization_id').references(() => organization.id, {
		onDelete: 'cascade',
	}),
	/** @deprecated Legacy client reference. Use organizationId instead. */
	clientId: text('client_id').references(() => client.id, { onDelete: 'set null' }),
	createdAt: timestamp('created_at').defaultNow().notNull(),
	updatedAt: timestamp('updated_at')
		.defaultNow()
		.$onUpdate(() => /* @__PURE__ */ new Date())
		.notNull(),
});

/**
 * Schedule Template table - reusable weekly templates per organization.
 */
export const scheduleTemplate = pgTable('schedule_template', {
	id: text('id')
		.primaryKey()
		.$defaultFn(() => randomUUID()),
	name: text('name').notNull(),
	description: text('description'),
	shiftType: shiftType('shift_type').default('DIURNA').notNull(),
	organizationId: text('organization_id')
		.notNull()
		.references(() => organization.id, { onDelete: 'cascade' }),
	createdAt: timestamp('created_at').defaultNow().notNull(),
	updatedAt: timestamp('updated_at')
		.defaultNow()
		.$onUpdate(() => /* @__PURE__ */ new Date())
		.notNull(),
});

/**
 * Schedule Template Day table - daily configuration for templates.
 */
export const scheduleTemplateDay = pgTable(
	'schedule_template_day',
	{
		id: text('id')
			.primaryKey()
			.$defaultFn(() => randomUUID()),
		templateId: text('template_id')
			.notNull()
			.references(() => scheduleTemplate.id, { onDelete: 'cascade' }),
		dayOfWeek: integer('day_of_week').notNull(), // 0=Sunday, 6=Saturday
		startTime: time('start_time', { withTimezone: false }).notNull(),
		endTime: time('end_time', { withTimezone: false }).notNull(),
		isWorkingDay: boolean('is_working_day').default(true).notNull(),
		createdAt: timestamp('created_at').defaultNow().notNull(),
		updatedAt: timestamp('updated_at')
			.defaultNow()
			.$onUpdate(() => /* @__PURE__ */ new Date())
			.notNull(),
	},
	(table) => [
		index('schedule_template_day_template_idx').on(table.templateId),
		uniqueIndex('schedule_template_day_uniq').on(table.templateId, table.dayOfWeek),
	],
);

/**
 * Employee table - stores employee information
 */
export const employee = pgTable(
	'employee',
	{
		id: text('id').primaryKey(),
		/** Unique employee code/badge number */
		code: text('code').notNull().unique(),
		firstName: text('first_name').notNull(),
		lastName: text('last_name').notNull(),
		/** Employee NSS (Número de Seguridad Social) */
		nss: text('nss'),
		/** Employee RFC (Registro Federal de Contribuyentes) */
		rfc: text('rfc'),
		email: text('email'),
		/** Contact phone number */
		phone: text('phone'),
		/** Reference to employee's job position */
		jobPositionId: text('job_position_id').references(() => jobPosition.id, {
			onDelete: 'set null',
		}),
		/** Department name */
		department: text('department'),
		/** Employee status (ACTIVE, INACTIVE, ON_LEAVE) */
		status: employeeStatus('status').default('ACTIVE').notNull(),
		/** Termination date key (YYYY-MM-DD) */
		terminationDateKey: text('termination_date_key'),
		/** Last day worked date key (YYYY-MM-DD) */
		lastDayWorkedDateKey: text('last_day_worked_date_key'),
		/** Termination reason (nullable until terminated) */
		terminationReason: terminationReason('termination_reason'),
		/** Employment contract type (nullable until terminated) */
		contractType: employmentContractType('contract_type'),
		/** Optional termination notes */
		terminationNotes: text('termination_notes'),
		/** Employee shift type used for hour limits */
		shiftType: shiftType('shift_type').default('DIURNA').notNull(),
		/** Date when employee was hired */
		hireDate: timestamp('hire_date'),
		/** Daily pay rate for payroll calculations (salario diario) */
		dailyPay: numeric('daily_pay', { precision: 10, scale: 2 }).default('0').notNull(),
		/** Payment frequency for this employee */
		paymentFrequency: paymentFrequency('payment_frequency').default('MONTHLY').notNull(),
		/** Employment type for PTU eligibility rules */
		employmentType: employmentType('employment_type').default('PERMANENT').notNull(),
		/** Trust employee flag (LFT 127-II) */
		isTrustEmployee: boolean('is_trust_employee').default(false).notNull(),
		/** Director/administrator/general manager flag (LFT 127-I) */
		isDirectorAdminGeneralManager: boolean('is_director_admin_general_manager')
			.default(false)
			.notNull(),
		/** Domestic worker flag (LFT 127-VI) */
		isDomesticWorker: boolean('is_domestic_worker').default(false).notNull(),
		/** Platform worker flag (LFT 127-IX) */
		isPlatformWorker: boolean('is_platform_worker').default(false).notNull(),
		/** Annual platform hours (used for PTU eligibility 288h rule) */
		platformHoursYear: numeric('platform_hours_year', { precision: 10, scale: 2 })
			.default('0')
			.notNull(),
		/** PTU eligibility override (DEFAULT/INCLUDE/EXCLUDE) */
		ptuEligibilityOverride: ptuEligibilityOverride('ptu_eligibility_override')
			.default('DEFAULT')
			.notNull(),
		/** Aguinaldo days override (per-employee total days) */
		aguinaldoDaysOverride: integer('aguinaldo_days_override'),
		/**
		 * Optional SBC daily override (Salario Base de Cotización diario).
		 * When provided, this value overrides the automatic SDI/SBC calculation.
		 */
		sbcDailyOverride: numeric('sbc_daily_override', { precision: 10, scale: 2 }),
		/** Location where employee works */
		locationId: text('location_id').references(() => location.id, { onDelete: 'set null' }),
		/** Assigned schedule template */
		scheduleTemplateId: text('schedule_template_id').references(() => scheduleTemplate.id, {
			onDelete: 'set null',
		}),
		/** Organization that the employee belongs to */
		organizationId: text('organization_id').references(() => organization.id, {
			onDelete: 'cascade',
		}),
		/** Linked BetterAuth user for self-service access */
		userId: text('user_id').references(() => user.id, { onDelete: 'set null' }),
		/**
		 * Last time payroll was processed for this employee.
		 * Set by payroll runs to avoid double-payment in a period.
		 */
		lastPayrollDate: timestamp('last_payroll_date'),
		/**
		 * Rekognition user ID for face recognition.
		 * Links the employee to their User Vector in the AWS Rekognition collection.
		 */
		rekognitionUserId: text('rekognition_user_id'),
		createdAt: timestamp('created_at').defaultNow().notNull(),
		updatedAt: timestamp('updated_at')
			.defaultNow()
			.$onUpdate(() => /* @__PURE__ */ new Date())
			.notNull(),
	},
	(table) => [uniqueIndex('employee_org_user_uniq').on(table.organizationId, table.userId)],
);

/**
 * Employee audit events - tracks changes to employee records.
 */
export const employeeAuditEvent = pgTable(
	'employee_audit_event',
	{
		id: text('id')
			.primaryKey()
			.$defaultFn(() => randomUUID()),
		employeeId: text('employee_id')
			.notNull()
			.references(() => employee.id, { onDelete: 'cascade' }),
		organizationId: text('organization_id').references(() => organization.id, {
			onDelete: 'cascade',
		}),
		action: text('action').notNull(),
		actorType: text('actor_type').notNull(),
		actorUserId: text('actor_user_id').references(() => user.id, { onDelete: 'set null' }),
		before: jsonb('before').$type<Record<string, unknown> | null>(),
		after: jsonb('after').$type<Record<string, unknown> | null>(),
		changedFields: jsonb('changed_fields').$type<string[]>().default([]).notNull(),
		createdAt: timestamp('created_at').defaultNow().notNull(),
	},
	(table) => [
		index('employee_audit_employee_idx').on(table.employeeId),
		index('employee_audit_org_idx').on(table.organizationId),
	],
);

/**
 * Employee termination settlements - auditable finiquito/liquidación snapshots.
 */
export const employeeTerminationSettlement = pgTable(
	'employee_termination_settlement',
	{
		id: text('id')
			.primaryKey()
			.$defaultFn(() => randomUUID()),
		employeeId: text('employee_id')
			.notNull()
			.references(() => employee.id, { onDelete: 'cascade' }),
		organizationId: text('organization_id').references(() => organization.id, {
			onDelete: 'cascade',
		}),
		calculation: jsonb('calculation').$type<EmployeeTerminationSettlement>().notNull(),
		totalsGross: numeric('totals_gross', { precision: 12, scale: 2 }).default('0').notNull(),
		finiquitoTotalGross: numeric('finiquito_total_gross', { precision: 12, scale: 2 })
			.default('0')
			.notNull(),
		liquidacionTotalGross: numeric('liquidacion_total_gross', { precision: 12, scale: 2 })
			.default('0')
			.notNull(),
		createdAt: timestamp('created_at').defaultNow().notNull(),
	},
	(table) => [
		index('employee_termination_settlement_employee_idx').on(table.employeeId),
		index('employee_termination_settlement_org_idx').on(table.organizationId),
	],
);

/**
 * Device table - stores kiosk/device information
 */
export const device = pgTable('device', {
	id: text('id').primaryKey(),
	/** Unique device code */
	code: text('code').notNull().unique(),
	/** Device name/label */
	name: text('name'),
	/** Type of device (TABLET, KIOSK, MOBILE) */
	deviceType: text('device_type'),
	/** Device status (ONLINE, OFFLINE, MAINTENANCE) */
	status: deviceStatus('status').default('OFFLINE').notNull(),
	/** Last time device sent a heartbeat */
	lastHeartbeat: timestamp('last_heartbeat'),
	/** Location where device is installed */
	locationId: text('location_id').references(() => location.id, { onDelete: 'set null' }),
	/** Organization that owns the device */
	organizationId: text('organization_id').references(() => organization.id, {
		onDelete: 'cascade',
	}),
	createdAt: timestamp('created_at').defaultNow().notNull(),
	updatedAt: timestamp('updated_at')
		.defaultNow()
		.$onUpdate(() => /* @__PURE__ */ new Date())
		.notNull(),
});

/**
 * AttendanceRecord table - stores attendance check-in/check-out records
 */
export const attendanceRecord = pgTable('attendance_record', {
	id: text('id').primaryKey(),
	employeeId: text('employee_id')
		.notNull()
		.references(() => employee.id, { onDelete: 'cascade' }),
	deviceId: text('device_id')
		.notNull()
		.references(() => device.id, { onDelete: 'cascade' }),
	timestamp: timestamp('timestamp').notNull(),
	type: attendanceType('type').notNull(),
	/**
	 * Business date key for offsite manual records in org timezone (YYYY-MM-DD).
	 */
	offsiteDateKey: text('offsite_date_key'),
	/**
	 * RH classification used for payroll treatment of offsite records.
	 */
	offsiteDayKind: offsiteDayKind('offsite_day_kind'),
	/**
	 * RH justification for offsite records.
	 */
	offsiteReason: text('offsite_reason'),
	/**
	 * User that created the offsite record.
	 */
	offsiteCreatedByUserId: text('offsite_created_by_user_id'),
	/**
	 * Last user that updated the offsite record.
	 */
	offsiteUpdatedByUserId: text('offsite_updated_by_user_id'),
	/**
	 * Last update timestamp for offsite record.
	 */
	offsiteUpdatedAt: timestamp('offsite_updated_at'),
	/**
	 * Additional metadata for Rekognition integration
	 * Stores match score, raw payload, face recognition data, etc.
	 */
	metadata: jsonb('metadata').$type<Record<string, unknown> | null>(),
	createdAt: timestamp('created_at').defaultNow().notNull(),
	updatedAt: timestamp('updated_at')
		.defaultNow()
		.$onUpdate(() => /* @__PURE__ */ new Date())
		.notNull(),
});

/**
 * Employee schedule table - stores weekly schedules per employee.
 */
export const employeeSchedule = pgTable(
	'employee_schedule',
	{
		id: text('id')
			.primaryKey()
			.$defaultFn(() => randomUUID()),
		employeeId: text('employee_id')
			.notNull()
			.references(() => employee.id, { onDelete: 'cascade' }),
		dayOfWeek: integer('day_of_week').notNull(), // 0 = Sunday, 6 = Saturday
		startTime: time('start_time', { withTimezone: false }).notNull(),
		endTime: time('end_time', { withTimezone: false }).notNull(),
		isWorkingDay: boolean('is_working_day').default(true).notNull(),
		createdAt: timestamp('created_at').defaultNow().notNull(),
		updatedAt: timestamp('updated_at')
			.defaultNow()
			.$onUpdate(() => /* @__PURE__ */ new Date())
			.notNull(),
	},
	(table) => [
		index('employee_schedule_employee_idx').on(table.employeeId),
		uniqueIndex('employee_schedule_employee_day_uniq').on(table.employeeId, table.dayOfWeek),
	],
);

/**
 * Vacation request table - stores vacation requests per employee.
 */
export const vacationRequest = pgTable(
	'vacation_request',
	{
		id: text('id')
			.primaryKey()
			.$defaultFn(() => randomUUID()),
		organizationId: text('organization_id')
			.notNull()
			.references(() => organization.id, { onDelete: 'cascade' }),
		employeeId: text('employee_id')
			.notNull()
			.references(() => employee.id, { onDelete: 'cascade' }),
		requestedByUserId: text('requested_by_user_id').references(() => user.id, {
			onDelete: 'set null',
		}),
		status: vacationRequestStatus('status').default('SUBMITTED').notNull(),
		startDateKey: text('start_date_key').notNull(),
		endDateKey: text('end_date_key').notNull(),
		requestedNotes: text('requested_notes'),
		decisionNotes: text('decision_notes'),
		approvedByUserId: text('approved_by_user_id').references(() => user.id, {
			onDelete: 'set null',
		}),
		approvedAt: timestamp('approved_at'),
		rejectedByUserId: text('rejected_by_user_id').references(() => user.id, {
			onDelete: 'set null',
		}),
		rejectedAt: timestamp('rejected_at'),
		cancelledByUserId: text('cancelled_by_user_id').references(() => user.id, {
			onDelete: 'set null',
		}),
		cancelledAt: timestamp('cancelled_at'),
		createdAt: timestamp('created_at').defaultNow().notNull(),
		updatedAt: timestamp('updated_at')
			.defaultNow()
			.$onUpdate(() => /* @__PURE__ */ new Date())
			.notNull(),
	},
	(table) => [
		index('vacation_request_org_status_idx').on(table.organizationId, table.status),
		index('vacation_request_employee_idx').on(table.employeeId),
		index('vacation_request_org_start_idx').on(table.organizationId, table.startDateKey),
		index('vacation_request_org_end_idx').on(table.organizationId, table.endDateKey),
	],
);

/**
 * Vacation request day table - stores per-day breakdown for requests.
 */
export const vacationRequestDay = pgTable(
	'vacation_request_day',
	{
		id: text('id')
			.primaryKey()
			.$defaultFn(() => randomUUID()),
		requestId: text('request_id')
			.notNull()
			.references(() => vacationRequest.id, { onDelete: 'cascade' }),
		employeeId: text('employee_id')
			.notNull()
			.references(() => employee.id, { onDelete: 'cascade' }),
		dateKey: text('date_key').notNull(),
		countsAsVacationDay: boolean('counts_as_vacation_day').default(false).notNull(),
		dayType: vacationDayType('day_type').notNull(),
		serviceYearNumber: integer('service_year_number'),
		createdAt: timestamp('created_at').defaultNow().notNull(),
	},
	(table) => [
		uniqueIndex('vacation_request_day_request_date_uniq').on(table.requestId, table.dateKey),
		index('vacation_request_day_employee_date_idx').on(table.employeeId, table.dateKey),
	],
);

/**
 * Employee incapacity table - stores IMSS incapacity/licence records.
 */
export const employeeIncapacity = pgTable(
	'employee_incapacity',
	{
		id: text('id')
			.primaryKey()
			.$defaultFn(() => randomUUID()),
		organizationId: text('organization_id')
			.notNull()
			.references(() => organization.id, { onDelete: 'cascade' }),
		employeeId: text('employee_id')
			.notNull()
			.references(() => employee.id, { onDelete: 'cascade' }),
		caseId: text('case_id').notNull(),
		type: incapacityType('type').notNull(),
		satTipoIncapacidad: satTipoIncapacidad('sat_tipo_incapacidad').notNull(),
		startDateKey: text('start_date_key').notNull(),
		endDateKey: text('end_date_key').notNull(),
		daysAuthorized: integer('days_authorized').notNull(),
		certificateFolio: text('certificate_folio'),
		issuedBy: incapacityIssuedBy('issued_by').default('IMSS').notNull(),
		sequence: incapacitySequence('sequence').default('inicial').notNull(),
		percentOverride: numeric('percent_override', { precision: 5, scale: 4 }),
		status: incapacityStatus('status').default('ACTIVE').notNull(),
		createdAt: timestamp('created_at').defaultNow().notNull(),
		updatedAt: timestamp('updated_at')
			.defaultNow()
			.$onUpdate(() => /* @__PURE__ */ new Date())
			.notNull(),
	},
	(table) => [
		index('employee_incapacity_org_employee_idx').on(table.organizationId, table.employeeId),
		index('employee_incapacity_org_status_idx').on(table.organizationId, table.status),
		index('employee_incapacity_org_start_idx').on(table.organizationId, table.startDateKey),
		index('employee_incapacity_org_end_idx').on(table.organizationId, table.endDateKey),
		index('employee_incapacity_employee_start_idx').on(table.employeeId, table.startDateKey),
	],
);

/**
 * Employee incapacity document table - stores uploaded IMSS documents.
 */
export const employeeIncapacityDocument = pgTable(
	'employee_incapacity_document',
	{
		id: text('id')
			.primaryKey()
			.$defaultFn(() => randomUUID()),
		incapacityId: text('incapacity_id')
			.notNull()
			.references(() => employeeIncapacity.id, { onDelete: 'cascade' }),
		bucket: text('bucket').notNull(),
		objectKey: text('object_key').notNull(),
		fileName: text('file_name').notNull(),
		contentType: text('content_type').notNull(),
		sizeBytes: integer('size_bytes').notNull(),
		sha256: text('sha256').notNull(),
		uploadedAt: timestamp('uploaded_at').defaultNow().notNull(),
		createdAt: timestamp('created_at').defaultNow().notNull(),
	},
	(table) => [uniqueIndex('employee_incapacity_document_object_key').on(table.objectKey)],
);

/**
 * Organization-level workflow configuration for employee document onboarding.
 */
export const organizationDocumentWorkflowConfig = pgTable(
	'organization_document_workflow_config',
	{
		id: text('id')
			.primaryKey()
			.$defaultFn(() => randomUUID()),
		organizationId: text('organization_id')
			.notNull()
			.unique()
			.references(() => organization.id, { onDelete: 'cascade' }),
		baseApprovedThresholdForLegal: integer('base_approved_threshold_for_legal')
			.default(1)
			.notNull(),
		createdAt: timestamp('created_at').defaultNow().notNull(),
		updatedAt: timestamp('updated_at')
			.defaultNow()
			.$onUpdate(() => /* @__PURE__ */ new Date())
			.notNull(),
	},
	(table) => [index('organization_document_workflow_config_org_idx').on(table.organizationId)],
);

/**
 * Organization-level document requirements with ordering and activation stage.
 */
export const organizationDocumentRequirement = pgTable(
	'organization_document_requirement',
	{
		id: text('id')
			.primaryKey()
			.$defaultFn(() => randomUUID()),
		organizationId: text('organization_id')
			.notNull()
			.references(() => organization.id, { onDelete: 'cascade' }),
		requirementKey: employeeDocumentRequirementKey('requirement_key').notNull(),
		isRequired: boolean('is_required').default(true).notNull(),
		displayOrder: integer('display_order').notNull(),
		activationStage: documentRequirementActivationStage('activation_stage')
			.default('BASE')
			.notNull(),
		createdAt: timestamp('created_at').defaultNow().notNull(),
		updatedAt: timestamp('updated_at')
			.defaultNow()
			.$onUpdate(() => /* @__PURE__ */ new Date())
			.notNull(),
	},
	(table) => [
		uniqueIndex('organization_document_requirement_org_key_uniq').on(
			table.organizationId,
			table.requirementKey,
		),
		index('organization_document_requirement_org_order_idx').on(
			table.organizationId,
			table.displayOrder,
		),
	],
);

/**
 * Organization-level branding values for legal templates and generated documents.
 */
export const organizationLegalBranding = pgTable(
	'organization_legal_branding',
	{
		id: text('id')
			.primaryKey()
			.$defaultFn(() => randomUUID()),
		organizationId: text('organization_id')
			.notNull()
			.unique()
			.references(() => organization.id, { onDelete: 'cascade' }),
		displayName: text('display_name'),
		headerText: text('header_text'),
		actaState: text('acta_state'),
		actaEmployerTreatment: text('acta_employer_treatment'),
		actaEmployerName: text('acta_employer_name'),
		actaEmployerPosition: text('acta_employer_position'),
		actaEmployeeTreatment: text('acta_employee_treatment'),
		logoBucket: text('logo_bucket'),
		logoObjectKey: text('logo_object_key'),
		logoFileName: text('logo_file_name'),
		logoContentType: text('logo_content_type'),
		logoSizeBytes: integer('logo_size_bytes'),
		logoSha256: text('logo_sha256'),
		createdAt: timestamp('created_at').defaultNow().notNull(),
		updatedAt: timestamp('updated_at')
			.defaultNow()
			.$onUpdate(() => /* @__PURE__ */ new Date())
			.notNull(),
	},
	(table) => [
		index('organization_legal_branding_org_idx').on(table.organizationId),
		uniqueIndex('organization_legal_branding_logo_object_key_uniq').on(table.logoObjectKey),
	],
);

/**
 * Versioned legal templates for contract and NDA generation per organization.
 */
export const organizationLegalTemplate = pgTable(
	'organization_legal_template',
	{
		id: text('id')
			.primaryKey()
			.$defaultFn(() => randomUUID()),
		organizationId: text('organization_id')
			.notNull()
			.references(() => organization.id, { onDelete: 'cascade' }),
		kind: legalDocumentKind('kind').notNull(),
		versionNumber: integer('version_number').notNull(),
		status: legalTemplateStatus('status').default('DRAFT').notNull(),
		htmlContent: text('html_content').notNull(),
		variablesSchemaSnapshot: jsonb('variables_schema_snapshot')
			.$type<Record<string, unknown>>()
			.default({})
			.notNull(),
		brandingSnapshot: jsonb('branding_snapshot').$type<Record<string, unknown> | null>(),
		createdByUserId: text('created_by_user_id').references(() => user.id, {
			onDelete: 'set null',
		}),
		publishedByUserId: text('published_by_user_id').references(() => user.id, {
			onDelete: 'set null',
		}),
		publishedAt: timestamp('published_at'),
		createdAt: timestamp('created_at').defaultNow().notNull(),
		updatedAt: timestamp('updated_at')
			.defaultNow()
			.$onUpdate(() => /* @__PURE__ */ new Date())
			.notNull(),
	},
	(table) => [
		uniqueIndex('organization_legal_template_org_kind_version_uniq').on(
			table.organizationId,
			table.kind,
			table.versionNumber,
		),
		index('organization_legal_template_org_kind_status_idx').on(
			table.organizationId,
			table.kind,
			table.status,
		),
	],
);

/**
 * Generated legal document instances tied to a specific employee and template version.
 */
export const employeeLegalGeneration = pgTable(
	'employee_legal_generation',
	{
		id: text('id')
			.primaryKey()
			.$defaultFn(() => randomUUID()),
		organizationId: text('organization_id')
			.notNull()
			.references(() => organization.id, { onDelete: 'cascade' }),
		employeeId: text('employee_id')
			.notNull()
			.references(() => employee.id, { onDelete: 'cascade' }),
		kind: legalDocumentKind('kind').notNull(),
		templateId: text('template_id')
			.notNull()
			.references(() => organizationLegalTemplate.id),
		templateVersionNumber: integer('template_version_number').notNull(),
		generatedHtmlHash: text('generated_html_hash').notNull(),
		generatedPdfHash: text('generated_pdf_hash'),
		variablesSnapshot: jsonb('variables_snapshot')
			.$type<Record<string, unknown>>()
			.default({})
			.notNull(),
		generatedByUserId: text('generated_by_user_id').references(() => user.id, {
			onDelete: 'set null',
		}),
		generatedAt: timestamp('generated_at').defaultNow().notNull(),
		createdAt: timestamp('created_at').defaultNow().notNull(),
		updatedAt: timestamp('updated_at')
			.defaultNow()
			.$onUpdate(() => /* @__PURE__ */ new Date())
			.notNull(),
	},
	(table) => [
		index('employee_legal_generation_org_employee_idx').on(
			table.organizationId,
			table.employeeId,
		),
		index('employee_legal_generation_employee_kind_idx').on(table.employeeId, table.kind),
		index('employee_legal_generation_template_idx').on(table.templateId),
	],
);

/**
 * Versioned employee document uploads and generated signed legal documents.
 */
export const employeeDocumentVersion = pgTable(
	'employee_document_version',
	{
		id: text('id')
			.primaryKey()
			.$defaultFn(() => randomUUID()),
		organizationId: text('organization_id')
			.notNull()
			.references(() => organization.id, { onDelete: 'cascade' }),
		employeeId: text('employee_id')
			.notNull()
			.references(() => employee.id, { onDelete: 'cascade' }),
		requirementKey: employeeDocumentRequirementKey('requirement_key').notNull(),
		versionNumber: integer('version_number').notNull(),
		isCurrent: boolean('is_current').default(true).notNull(),
		reviewStatus: employeeDocumentReviewStatus('review_status')
			.default('PENDING_REVIEW')
			.notNull(),
		reviewComment: text('review_comment'),
		reviewedByUserId: text('reviewed_by_user_id').references(() => user.id, {
			onDelete: 'set null',
		}),
		reviewedAt: timestamp('reviewed_at'),
		source: employeeDocumentSource('source').default('UPLOAD').notNull(),
		generationId: text('generation_id').references(() => employeeLegalGeneration.id),
		identificationSubtype: identificationSubtype('identification_subtype'),
		employmentProfileSubtype: employmentProfileSubtype('employment_profile_subtype'),
		signedAtDateKey: text('signed_at_date_key'),
		verifiedByUserId: text('verified_by_user_id').references(() => user.id, {
			onDelete: 'set null',
		}),
		bucket: text('bucket').notNull(),
		objectKey: text('object_key').notNull(),
		fileName: text('file_name').notNull(),
		contentType: text('content_type').notNull(),
		sizeBytes: integer('size_bytes').notNull(),
		sha256: text('sha256').notNull(),
		uploadedByUserId: text('uploaded_by_user_id').references(() => user.id, {
			onDelete: 'set null',
		}),
		uploadedAt: timestamp('uploaded_at').defaultNow().notNull(),
		metadata: jsonb('metadata').$type<Record<string, unknown> | null>(),
		createdAt: timestamp('created_at').defaultNow().notNull(),
		updatedAt: timestamp('updated_at')
			.defaultNow()
			.$onUpdate(() => /* @__PURE__ */ new Date())
			.notNull(),
	},
	(table) => [
		uniqueIndex('employee_document_version_employee_requirement_version_uniq').on(
			table.employeeId,
			table.requirementKey,
			table.versionNumber,
		),
		uniqueIndex('employee_document_version_object_key_uniq').on(table.objectKey),
		uniqueIndex('employee_document_version_generation_uniq').on(table.generationId),
		index('employee_document_version_org_employee_idx').on(
			table.organizationId,
			table.employeeId,
		),
		index('employee_document_version_org_employee_current_idx').on(
			table.organizationId,
			table.employeeId,
			table.isCurrent,
		),
		index('employee_document_version_org_current_review_idx').on(
			table.organizationId,
			table.isCurrent,
			table.reviewStatus,
		),
		index('employee_document_version_employee_requirement_idx').on(
			table.employeeId,
			table.requirementKey,
		),
	],
);

/**
 * Per-organization disciplinary folio counter.
 * The sequence is monotonic and may contain gaps.
 */
export const organizationDisciplinaryFolioCounter = pgTable(
	'organization_disciplinary_folio_counter',
	{
		id: text('id')
			.primaryKey()
			.$defaultFn(() => randomUUID()),
		organizationId: text('organization_id')
			.notNull()
			.unique()
			.references(() => organization.id, { onDelete: 'cascade' }),
		lastFolio: integer('last_folio').default(0).notNull(),
		createdAt: timestamp('created_at').defaultNow().notNull(),
		updatedAt: timestamp('updated_at')
			.defaultNow()
			.$onUpdate(() => /* @__PURE__ */ new Date())
			.notNull(),
	},
	(table) => [index('organization_disciplinary_folio_counter_org_idx').on(table.organizationId)],
);

/**
 * Disciplinary measures issued per employee.
 */
export const employeeDisciplinaryMeasure = pgTable(
	'employee_disciplinary_measure',
	{
		id: text('id')
			.primaryKey()
			.$defaultFn(() => randomUUID()),
		organizationId: text('organization_id')
			.notNull()
			.references(() => organization.id, { onDelete: 'cascade' }),
		employeeId: text('employee_id')
			.notNull()
			.references(() => employee.id, { onDelete: 'cascade' }),
		folio: integer('folio').notNull(),
		status: disciplinaryMeasureStatus('status').default('DRAFT').notNull(),
		incidentDateKey: text('incident_date_key').notNull(),
		reason: text('reason').notNull(),
		policyReference: text('policy_reference'),
		notes: text('notes'),
		outcome: disciplinaryOutcome('outcome').default('no_action').notNull(),
		suspensionStartDateKey: text('suspension_start_date_key'),
		suspensionEndDateKey: text('suspension_end_date_key'),
		signatureStatus: disciplinarySignatureStatus('signature_status'),
		generatedActaGenerationId: text('generated_acta_generation_id').references(
			() => employeeLegalGeneration.id,
			{ onDelete: 'set null' },
		),
		generatedRefusalGenerationId: text('generated_refusal_generation_id').references(
			() => employeeLegalGeneration.id,
			{ onDelete: 'set null' },
		),
		closedAt: timestamp('closed_at'),
		closedByUserId: text('closed_by_user_id').references(() => user.id, {
			onDelete: 'set null',
		}),
		createdByUserId: text('created_by_user_id').references(() => user.id, {
			onDelete: 'set null',
		}),
		updatedByUserId: text('updated_by_user_id').references(() => user.id, {
			onDelete: 'set null',
		}),
		createdAt: timestamp('created_at').defaultNow().notNull(),
		updatedAt: timestamp('updated_at')
			.defaultNow()
			.$onUpdate(() => /* @__PURE__ */ new Date())
			.notNull(),
	},
	(table) => [
		uniqueIndex('employee_disciplinary_measure_org_folio_uniq').on(
			table.organizationId,
			table.folio,
		),
		index('employee_disciplinary_measure_org_incident_date_idx').on(
			table.organizationId,
			table.incidentDateKey,
		),
		index('employee_disciplinary_measure_org_employee_idx').on(
			table.organizationId,
			table.employeeId,
		),
		index('employee_disciplinary_measure_org_status_idx').on(
			table.organizationId,
			table.status,
		),
		index('employee_disciplinary_measure_org_outcome_idx').on(
			table.organizationId,
			table.outcome,
		),
	],
);

/**
 * Versioned signed disciplinary files generated from legal templates.
 */
export const employeeDisciplinaryDocumentVersion = pgTable(
	'employee_disciplinary_document_version',
	{
		id: text('id')
			.primaryKey()
			.$defaultFn(() => randomUUID()),
		organizationId: text('organization_id')
			.notNull()
			.references(() => organization.id, { onDelete: 'cascade' }),
		employeeId: text('employee_id')
			.notNull()
			.references(() => employee.id, { onDelete: 'cascade' }),
		measureId: text('measure_id')
			.notNull()
			.references(() => employeeDisciplinaryMeasure.id, { onDelete: 'cascade' }),
		kind: disciplinaryDocumentKind('kind').notNull(),
		versionNumber: integer('version_number').notNull(),
		isCurrent: boolean('is_current').default(true).notNull(),
		generationId: text('generation_id').references(() => employeeLegalGeneration.id, {
			onDelete: 'set null',
		}),
		signedAtDateKey: text('signed_at_date_key'),
		bucket: text('bucket').notNull(),
		objectKey: text('object_key').notNull(),
		fileName: text('file_name').notNull(),
		contentType: text('content_type').notNull(),
		sizeBytes: integer('size_bytes').notNull(),
		sha256: text('sha256').notNull(),
		uploadedByUserId: text('uploaded_by_user_id').references(() => user.id, {
			onDelete: 'set null',
		}),
		uploadedAt: timestamp('uploaded_at').defaultNow().notNull(),
		metadata: jsonb('metadata').$type<Record<string, unknown> | null>(),
		createdAt: timestamp('created_at').defaultNow().notNull(),
		updatedAt: timestamp('updated_at')
			.defaultNow()
			.$onUpdate(() => /* @__PURE__ */ new Date())
			.notNull(),
	},
	(table) => [
		uniqueIndex('employee_disciplinary_document_measure_kind_version_uniq').on(
			table.measureId,
			table.kind,
			table.versionNumber,
		),
		uniqueIndex('employee_disciplinary_document_object_key_uniq').on(table.objectKey),
		index('employee_disciplinary_document_measure_idx').on(table.measureId),
	],
);

/**
 * Additional disciplinary evidence attachments.
 */
export const employeeDisciplinaryAttachment = pgTable(
	'employee_disciplinary_attachment',
	{
		id: text('id')
			.primaryKey()
			.$defaultFn(() => randomUUID()),
		organizationId: text('organization_id')
			.notNull()
			.references(() => organization.id, { onDelete: 'cascade' }),
		employeeId: text('employee_id')
			.notNull()
			.references(() => employee.id, { onDelete: 'cascade' }),
		measureId: text('measure_id')
			.notNull()
			.references(() => employeeDisciplinaryMeasure.id, { onDelete: 'cascade' }),
		bucket: text('bucket').notNull(),
		objectKey: text('object_key').notNull(),
		fileName: text('file_name').notNull(),
		contentType: text('content_type').notNull(),
		sizeBytes: integer('size_bytes').notNull(),
		sha256: text('sha256').notNull(),
		uploadedByUserId: text('uploaded_by_user_id').references(() => user.id, {
			onDelete: 'set null',
		}),
		uploadedAt: timestamp('uploaded_at').defaultNow().notNull(),
		metadata: jsonb('metadata').$type<Record<string, unknown> | null>(),
		createdAt: timestamp('created_at').defaultNow().notNull(),
		updatedAt: timestamp('updated_at')
			.defaultNow()
			.$onUpdate(() => /* @__PURE__ */ new Date())
			.notNull(),
	},
	(table) => [
		uniqueIndex('employee_disciplinary_attachment_object_key_uniq').on(table.objectKey),
		index('employee_disciplinary_attachment_measure_idx').on(table.measureId),
	],
);

/**
 * Termination drafts created from disciplinary outcomes.
 */
export const employeeTerminationDraft = pgTable(
	'employee_termination_draft',
	{
		id: text('id')
			.primaryKey()
			.$defaultFn(() => randomUUID()),
		organizationId: text('organization_id')
			.notNull()
			.references(() => organization.id, { onDelete: 'cascade' }),
		employeeId: text('employee_id')
			.notNull()
			.references(() => employee.id, { onDelete: 'cascade' }),
		measureId: text('measure_id')
			.notNull()
			.references(() => employeeDisciplinaryMeasure.id, { onDelete: 'cascade' }),
		status: terminationDraftStatus('status').default('ACTIVE').notNull(),
		payload: jsonb('payload').$type<Record<string, unknown>>().default({}).notNull(),
		consumedAt: timestamp('consumed_at'),
		cancelledAt: timestamp('cancelled_at'),
		createdByUserId: text('created_by_user_id').references(() => user.id, {
			onDelete: 'set null',
		}),
		updatedByUserId: text('updated_by_user_id').references(() => user.id, {
			onDelete: 'set null',
		}),
		createdAt: timestamp('created_at').defaultNow().notNull(),
		updatedAt: timestamp('updated_at')
			.defaultNow()
			.$onUpdate(() => /* @__PURE__ */ new Date())
			.notNull(),
	},
	(table) => [
		uniqueIndex('employee_termination_draft_measure_uniq').on(table.measureId),
		index('employee_termination_draft_org_employee_status_idx').on(
			table.organizationId,
			table.employeeId,
			table.status,
		),
	],
);

/**
 * Schedule Exception table - date-specific overrides for employee schedules.
 */
export const scheduleException = pgTable(
	'schedule_exception',
	{
		id: text('id')
			.primaryKey()
			.$defaultFn(() => randomUUID()),
		employeeId: text('employee_id')
			.notNull()
			.references(() => employee.id, { onDelete: 'cascade' }),
		exceptionDate: timestamp('exception_date').notNull(),
		exceptionType: scheduleExceptionType('exception_type').notNull(),
		startTime: time('start_time', { withTimezone: false }),
		endTime: time('end_time', { withTimezone: false }),
		reason: text('reason'),
		vacationRequestId: text('vacation_request_id').references(() => vacationRequest.id, {
			onDelete: 'set null',
		}),
		incapacityId: text('incapacity_id').references(() => employeeIncapacity.id, {
			onDelete: 'set null',
		}),
		createdAt: timestamp('created_at').defaultNow().notNull(),
		updatedAt: timestamp('updated_at')
			.defaultNow()
			.$onUpdate(() => /* @__PURE__ */ new Date())
			.notNull(),
	},
	(table) => [
		index('schedule_exception_employee_idx').on(table.employeeId),
		index('schedule_exception_date_idx').on(table.exceptionDate),
		uniqueIndex('schedule_exception_employee_date_uniq').on(
			table.employeeId,
			table.exceptionDate,
		),
	],
);

/**
 * Payroll settings per organization.
 */
export const payrollSetting = pgTable('payroll_setting', {
	id: text('id')
		.primaryKey()
		.$defaultFn(() => randomUUID()),
	organizationId: text('organization_id')
		.notNull()
		.unique()
		.references(() => organization.id, { onDelete: 'cascade' }),
	/**
	 * IANA timezone identifier for payroll periods (used for start/end boundaries).
	 *
	 * Examples: "America/Mexico_City", "America/Tijuana"
	 */
	timeZone: text('time_zone').default('America/Mexico_City').notNull(),
	weekStartDay: integer('week_start_day').default(1).notNull(), // default Monday
	/** Behavior when overtime limits are exceeded */
	overtimeEnforcement: overtimeEnforcement('overtime_enforcement').default('WARN').notNull(),
	/**
	 * Additional mandatory rest days (YYYY-MM-DD) configured per organization.
	 *
	 * Used primarily for Art. 74 fr. IX ("jornada electoral") and other local/organizational
	 * rest days that are date-specific.
	 */
	additionalMandatoryRestDays: jsonb('additional_mandatory_rest_days')
		.$type<string[]>()
		.default([])
		.notNull(),
	/** Risk of work rate (prima de riesgo de trabajo) */
	riskWorkRate: numeric('risk_work_rate', { precision: 6, scale: 4 }).default('0').notNull(),
	/** State payroll tax rate (ISN) */
	statePayrollTaxRate: numeric('state_payroll_tax_rate', { precision: 6, scale: 4 })
		.default('0')
		.notNull(),
	/** Whether the employer absorbs the employee IMSS share */
	absorbImssEmployeeShare: boolean('absorb_imss_employee_share').default(false).notNull(),
	/** Whether the employer absorbs ISR withholding */
	absorbIsr: boolean('absorb_isr').default(false).notNull(),
	/** Aguinaldo days for SDI/SBC integration factor */
	aguinaldoDays: integer('aguinaldo_days').default(15).notNull(),
	/** Vacation premium rate for SDI/SBC integration factor */
	vacationPremiumRate: numeric('vacation_premium_rate', { precision: 6, scale: 4 })
		.default('0.25')
		.notNull(),
	/** Enables the seventh day pay calculation */
	enableSeventhDayPay: boolean('enable_seventh_day_pay').default(false).notNull(),
	/** Whether PTU calculations are enabled */
	ptuEnabled: boolean('ptu_enabled').default(false).notNull(),
	/** PTU mode behavior (DEFAULT_RULES or MANUAL) */
	ptuMode: ptuMode('ptu_mode').default('DEFAULT_RULES').notNull(),
	/** Whether the employer is exempt from PTU */
	ptuIsExempt: boolean('ptu_is_exempt').default(false).notNull(),
	/** Optional PTU exemption reason code/text */
	ptuExemptReason: text('ptu_exempt_reason'),
	/** Employer type (persona moral/física) for PTU timelines */
	employerType: employerType('employer_type').default('PERSONA_MORAL').notNull(),
	/** Whether aguinaldo calculations are enabled */
	aguinaldoEnabled: boolean('aguinaldo_enabled').default(true).notNull(),
	/** Enables disciplinary measures module for this organization. */
	enableDisciplinaryMeasures: boolean('enable_disciplinary_measures').default(true).notNull(),
	createdAt: timestamp('created_at').defaultNow().notNull(),
	updatedAt: timestamp('updated_at')
		.defaultNow()
		.$onUpdate(() => /* @__PURE__ */ new Date())
		.notNull(),
});

/**
 * Holiday sync run table - tracks provider sync executions by organization/year.
 */
export const holidaySyncRun = pgTable(
	'holiday_sync_run',
	{
		id: text('id')
			.primaryKey()
			.$defaultFn(() => randomUUID()),
		organizationId: text('organization_id').references(() => organization.id, {
			onDelete: 'cascade',
		}),
		provider: text('provider').notNull().default('NAGER_DATE'),
		requestedYears: jsonb('requested_years').$type<number[]>().default([]).notNull(),
		status: holidaySyncRunStatus('status').default('RUNNING').notNull(),
		startedAt: timestamp('started_at').defaultNow().notNull(),
		finishedAt: timestamp('finished_at'),
		importedCount: integer('imported_count').default(0).notNull(),
		pendingCount: integer('pending_count').default(0).notNull(),
		errorCount: integer('error_count').default(0).notNull(),
		errorPayload: jsonb('error_payload').$type<Record<string, unknown> | null>(),
		stale: boolean('stale').default(false).notNull(),
		createdAt: timestamp('created_at').defaultNow().notNull(),
		updatedAt: timestamp('updated_at')
			.defaultNow()
			.$onUpdate(() => /* @__PURE__ */ new Date())
			.notNull(),
	},
	(table) => [
		index('holiday_sync_run_org_idx').on(table.organizationId),
		index('holiday_sync_run_status_idx').on(table.status),
	],
);

/**
 * Holiday calendar entries per organization.
 */
export const holidayCalendarEntry = pgTable(
	'holiday_calendar_entry',
	{
		id: text('id')
			.primaryKey()
			.$defaultFn(() => randomUUID()),
		organizationId: text('organization_id')
			.notNull()
			.references(() => organization.id, { onDelete: 'cascade' }),
		dateKey: text('date_key').notNull(),
		name: text('name').notNull(),
		kind: holidayKind('kind').default('MANDATORY').notNull(),
		source: holidaySource('source').notNull(),
		status: holidayStatus('status').default('PENDING_APPROVAL').notNull(),
		isRecurring: boolean('is_recurring').default(false).notNull(),
		seriesId: text('series_id'),
		provider: text('provider'),
		providerExternalId: text('provider_external_id'),
		subdivisionCode: text('subdivision_code'),
		legalReference: text('legal_reference'),
		conflictReason: text('conflict_reason'),
		active: boolean('active').default(true).notNull(),
		entryKey: text('entry_key').default('').notNull(),
		syncRunId: text('sync_run_id').references(() => holidaySyncRun.id, {
			onDelete: 'set null',
		}),
		approvedBy: text('approved_by').references(() => user.id, { onDelete: 'set null' }),
		approvedAt: timestamp('approved_at'),
		rejectedBy: text('rejected_by').references(() => user.id, { onDelete: 'set null' }),
		rejectedAt: timestamp('rejected_at'),
		createdAt: timestamp('created_at').defaultNow().notNull(),
		updatedAt: timestamp('updated_at')
			.defaultNow()
			.$onUpdate(() => /* @__PURE__ */ new Date())
			.notNull(),
	},
	(table) => [
		index('holiday_entry_org_date_idx').on(table.organizationId, table.dateKey),
		index('holiday_entry_org_status_idx').on(table.organizationId, table.status),
		index('holiday_entry_org_source_idx').on(table.organizationId, table.source),
		index('holiday_entry_sync_run_idx').on(table.syncRunId),
		uniqueIndex('holiday_entry_org_date_source_key_uniq').on(
			table.organizationId,
			table.dateKey,
			table.source,
			table.entryKey,
		),
	],
);

/**
 * Holiday audit event table.
 */
export const holidayAuditEvent = pgTable(
	'holiday_audit_event',
	{
		id: text('id')
			.primaryKey()
			.$defaultFn(() => randomUUID()),
		organizationId: text('organization_id')
			.notNull()
			.references(() => organization.id, { onDelete: 'cascade' }),
		holidayEntryId: text('holiday_entry_id').references(() => holidayCalendarEntry.id, {
			onDelete: 'set null',
		}),
		syncRunId: text('sync_run_id').references(() => holidaySyncRun.id, {
			onDelete: 'set null',
		}),
		actorType: text('actor_type').notNull(),
		actorUserId: text('actor_user_id').references(() => user.id, { onDelete: 'set null' }),
		action: text('action').notNull(),
		reason: text('reason'),
		before: jsonb('before').$type<Record<string, unknown> | null>(),
		after: jsonb('after').$type<Record<string, unknown> | null>(),
		metadata: jsonb('metadata').$type<Record<string, unknown> | null>(),
		createdAt: timestamp('created_at').defaultNow().notNull(),
	},
	(table) => [
		index('holiday_audit_org_idx').on(table.organizationId),
		index('holiday_audit_entry_idx').on(table.holidayEntryId),
		index('holiday_audit_sync_idx').on(table.syncRunId),
	],
);

// ============================================================================
// Relations - Scheduling
// ============================================================================

export const scheduleTemplateRelations = relations(scheduleTemplate, ({ one, many }) => ({
	organization: one(organization, {
		fields: [scheduleTemplate.organizationId],
		references: [organization.id],
	}),
	days: many(scheduleTemplateDay),
	employees: many(employee),
}));

export const scheduleTemplateDayRelations = relations(scheduleTemplateDay, ({ one }) => ({
	template: one(scheduleTemplate, {
		fields: [scheduleTemplateDay.templateId],
		references: [scheduleTemplate.id],
	}),
}));

export const employeeRelations = relations(employee, ({ one, many }) => ({
	jobPosition: one(jobPosition, {
		fields: [employee.jobPositionId],
		references: [jobPosition.id],
	}),
	location: one(location, {
		fields: [employee.locationId],
		references: [location.id],
	}),
	organization: one(organization, {
		fields: [employee.organizationId],
		references: [organization.id],
	}),
	scheduleTemplate: one(scheduleTemplate, {
		fields: [employee.scheduleTemplateId],
		references: [scheduleTemplate.id],
	}),
	user: one(user, {
		fields: [employee.userId],
		references: [user.id],
	}),
	scheduleEntries: many(employeeSchedule),
	scheduleExceptions: many(scheduleException),
	incapacities: many(employeeIncapacity),
	vacationRequests: many(vacationRequest),
	vacationRequestDays: many(vacationRequestDay),
	auditEvents: many(employeeAuditEvent),
	terminationSettlements: many(employeeTerminationSettlement),
	legalGenerations: many(employeeLegalGeneration),
	documentVersions: many(employeeDocumentVersion),
	disciplinaryMeasures: many(employeeDisciplinaryMeasure),
	disciplinaryDocumentVersions: many(employeeDisciplinaryDocumentVersion),
	disciplinaryAttachments: many(employeeDisciplinaryAttachment),
	terminationDrafts: many(employeeTerminationDraft),
	overtimeAuthorizations: many(overtimeAuthorization),
}));

export const employeeAuditEventRelations = relations(employeeAuditEvent, ({ one }) => ({
	employee: one(employee, {
		fields: [employeeAuditEvent.employeeId],
		references: [employee.id],
	}),
	organization: one(organization, {
		fields: [employeeAuditEvent.organizationId],
		references: [organization.id],
	}),
	actor: one(user, {
		fields: [employeeAuditEvent.actorUserId],
		references: [user.id],
	}),
}));

export const employeeTerminationSettlementRelations = relations(
	employeeTerminationSettlement,
	({ one }) => ({
		employee: one(employee, {
			fields: [employeeTerminationSettlement.employeeId],
			references: [employee.id],
		}),
		organization: one(organization, {
			fields: [employeeTerminationSettlement.organizationId],
			references: [organization.id],
		}),
	}),
);

export const scheduleExceptionRelations = relations(scheduleException, ({ one }) => ({
	employee: one(employee, {
		fields: [scheduleException.employeeId],
		references: [employee.id],
	}),
	vacationRequest: one(vacationRequest, {
		fields: [scheduleException.vacationRequestId],
		references: [vacationRequest.id],
	}),
	incapacity: one(employeeIncapacity, {
		fields: [scheduleException.incapacityId],
		references: [employeeIncapacity.id],
	}),
}));

export const employeeIncapacityRelations = relations(employeeIncapacity, ({ one, many }) => ({
	organization: one(organization, {
		fields: [employeeIncapacity.organizationId],
		references: [organization.id],
	}),
	employee: one(employee, {
		fields: [employeeIncapacity.employeeId],
		references: [employee.id],
	}),
	documents: many(employeeIncapacityDocument),
	scheduleExceptions: many(scheduleException),
}));

export const employeeIncapacityDocumentRelations = relations(
	employeeIncapacityDocument,
	({ one }) => ({
		incapacity: one(employeeIncapacity, {
			fields: [employeeIncapacityDocument.incapacityId],
			references: [employeeIncapacity.id],
		}),
	}),
);

export const organizationDocumentWorkflowConfigRelations = relations(
	organizationDocumentWorkflowConfig,
	({ one }) => ({
		organization: one(organization, {
			fields: [organizationDocumentWorkflowConfig.organizationId],
			references: [organization.id],
		}),
	}),
);

export const organizationDocumentRequirementRelations = relations(
	organizationDocumentRequirement,
	({ one }) => ({
		organization: one(organization, {
			fields: [organizationDocumentRequirement.organizationId],
			references: [organization.id],
		}),
	}),
);

export const organizationLegalBrandingRelations = relations(
	organizationLegalBranding,
	({ one }) => ({
		organization: one(organization, {
			fields: [organizationLegalBranding.organizationId],
			references: [organization.id],
		}),
	}),
);

export const organizationLegalTemplateRelations = relations(
	organizationLegalTemplate,
	({ one, many }) => ({
		organization: one(organization, {
			fields: [organizationLegalTemplate.organizationId],
			references: [organization.id],
		}),
		createdBy: one(user, {
			fields: [organizationLegalTemplate.createdByUserId],
			references: [user.id],
		}),
		publishedBy: one(user, {
			fields: [organizationLegalTemplate.publishedByUserId],
			references: [user.id],
		}),
		generations: many(employeeLegalGeneration),
	}),
);

export const employeeLegalGenerationRelations = relations(
	employeeLegalGeneration,
	({ one, many }) => ({
		organization: one(organization, {
			fields: [employeeLegalGeneration.organizationId],
			references: [organization.id],
		}),
		employee: one(employee, {
			fields: [employeeLegalGeneration.employeeId],
			references: [employee.id],
		}),
		template: one(organizationLegalTemplate, {
			fields: [employeeLegalGeneration.templateId],
			references: [organizationLegalTemplate.id],
		}),
		generatedBy: one(user, {
			fields: [employeeLegalGeneration.generatedByUserId],
			references: [user.id],
		}),
		documentVersions: many(employeeDocumentVersion),
		disciplinaryDocumentVersions: many(employeeDisciplinaryDocumentVersion),
		disciplinaryActaMeasures: many(employeeDisciplinaryMeasure, {
			relationName: 'disciplinaryActaGeneration',
		}),
		disciplinaryRefusalMeasures: many(employeeDisciplinaryMeasure, {
			relationName: 'disciplinaryRefusalGeneration',
		}),
	}),
);

export const employeeDocumentVersionRelations = relations(employeeDocumentVersion, ({ one }) => ({
	organization: one(organization, {
		fields: [employeeDocumentVersion.organizationId],
		references: [organization.id],
	}),
	employee: one(employee, {
		fields: [employeeDocumentVersion.employeeId],
		references: [employee.id],
	}),
	reviewedBy: one(user, {
		fields: [employeeDocumentVersion.reviewedByUserId],
		references: [user.id],
	}),
	verifiedBy: one(user, {
		fields: [employeeDocumentVersion.verifiedByUserId],
		references: [user.id],
	}),
	uploadedBy: one(user, {
		fields: [employeeDocumentVersion.uploadedByUserId],
		references: [user.id],
	}),
	generation: one(employeeLegalGeneration, {
		fields: [employeeDocumentVersion.generationId],
		references: [employeeLegalGeneration.id],
	}),
}));

export const organizationDisciplinaryFolioCounterRelations = relations(
	organizationDisciplinaryFolioCounter,
	({ one }) => ({
		organization: one(organization, {
			fields: [organizationDisciplinaryFolioCounter.organizationId],
			references: [organization.id],
		}),
	}),
);

export const employeeDisciplinaryMeasureRelations = relations(
	employeeDisciplinaryMeasure,
	({ one, many }) => ({
		organization: one(organization, {
			fields: [employeeDisciplinaryMeasure.organizationId],
			references: [organization.id],
		}),
		employee: one(employee, {
			fields: [employeeDisciplinaryMeasure.employeeId],
			references: [employee.id],
		}),
		actaGeneration: one(employeeLegalGeneration, {
			relationName: 'disciplinaryActaGeneration',
			fields: [employeeDisciplinaryMeasure.generatedActaGenerationId],
			references: [employeeLegalGeneration.id],
		}),
		refusalGeneration: one(employeeLegalGeneration, {
			relationName: 'disciplinaryRefusalGeneration',
			fields: [employeeDisciplinaryMeasure.generatedRefusalGenerationId],
			references: [employeeLegalGeneration.id],
		}),
		closedBy: one(user, {
			relationName: 'disciplinaryMeasureClosedBy',
			fields: [employeeDisciplinaryMeasure.closedByUserId],
			references: [user.id],
		}),
		createdBy: one(user, {
			relationName: 'disciplinaryMeasureCreatedBy',
			fields: [employeeDisciplinaryMeasure.createdByUserId],
			references: [user.id],
		}),
		updatedBy: one(user, {
			relationName: 'disciplinaryMeasureUpdatedBy',
			fields: [employeeDisciplinaryMeasure.updatedByUserId],
			references: [user.id],
		}),
		documentVersions: many(employeeDisciplinaryDocumentVersion),
		attachments: many(employeeDisciplinaryAttachment),
		terminationDrafts: many(employeeTerminationDraft),
	}),
);

export const employeeDisciplinaryDocumentVersionRelations = relations(
	employeeDisciplinaryDocumentVersion,
	({ one }) => ({
		organization: one(organization, {
			fields: [employeeDisciplinaryDocumentVersion.organizationId],
			references: [organization.id],
		}),
		employee: one(employee, {
			fields: [employeeDisciplinaryDocumentVersion.employeeId],
			references: [employee.id],
		}),
		measure: one(employeeDisciplinaryMeasure, {
			fields: [employeeDisciplinaryDocumentVersion.measureId],
			references: [employeeDisciplinaryMeasure.id],
		}),
		generation: one(employeeLegalGeneration, {
			fields: [employeeDisciplinaryDocumentVersion.generationId],
			references: [employeeLegalGeneration.id],
		}),
		uploadedBy: one(user, {
			fields: [employeeDisciplinaryDocumentVersion.uploadedByUserId],
			references: [user.id],
		}),
	}),
);

export const employeeDisciplinaryAttachmentRelations = relations(
	employeeDisciplinaryAttachment,
	({ one }) => ({
		organization: one(organization, {
			fields: [employeeDisciplinaryAttachment.organizationId],
			references: [organization.id],
		}),
		employee: one(employee, {
			fields: [employeeDisciplinaryAttachment.employeeId],
			references: [employee.id],
		}),
		measure: one(employeeDisciplinaryMeasure, {
			fields: [employeeDisciplinaryAttachment.measureId],
			references: [employeeDisciplinaryMeasure.id],
		}),
		uploadedBy: one(user, {
			fields: [employeeDisciplinaryAttachment.uploadedByUserId],
			references: [user.id],
		}),
	}),
);

export const employeeTerminationDraftRelations = relations(employeeTerminationDraft, ({ one }) => ({
	organization: one(organization, {
		fields: [employeeTerminationDraft.organizationId],
		references: [organization.id],
	}),
	employee: one(employee, {
		fields: [employeeTerminationDraft.employeeId],
		references: [employee.id],
	}),
	measure: one(employeeDisciplinaryMeasure, {
		fields: [employeeTerminationDraft.measureId],
		references: [employeeDisciplinaryMeasure.id],
	}),
	createdBy: one(user, {
		relationName: 'terminationDraftCreatedBy',
		fields: [employeeTerminationDraft.createdByUserId],
		references: [user.id],
	}),
	updatedBy: one(user, {
		relationName: 'terminationDraftUpdatedBy',
		fields: [employeeTerminationDraft.updatedByUserId],
		references: [user.id],
	}),
}));

export const vacationRequestRelations = relations(vacationRequest, ({ one, many }) => ({
	organization: one(organization, {
		fields: [vacationRequest.organizationId],
		references: [organization.id],
	}),
	employee: one(employee, {
		fields: [vacationRequest.employeeId],
		references: [employee.id],
	}),
	days: many(vacationRequestDay),
}));

export const vacationRequestDayRelations = relations(vacationRequestDay, ({ one }) => ({
	request: one(vacationRequest, {
		fields: [vacationRequestDay.requestId],
		references: [vacationRequest.id],
	}),
	employee: one(employee, {
		fields: [vacationRequestDay.employeeId],
		references: [employee.id],
	}),
}));

/**
 * Overtime authorizations approved before the worked date.
 */
export const overtimeAuthorization = pgTable(
	'overtime_authorization',
	{
		id: text('id')
			.primaryKey()
			.$defaultFn(() => randomUUID()),
		organizationId: text('organization_id')
			.notNull()
			.references(() => organization.id, { onDelete: 'cascade' }),
		employeeId: text('employee_id')
			.notNull()
			.references(() => employee.id, { onDelete: 'cascade' }),
		dateKey: text('date_key').notNull(),
		authorizedHours: numeric('authorized_hours', { precision: 5, scale: 2 }).notNull(),
		authorizedByUserId: text('authorized_by_user_id').references(() => user.id, {
			onDelete: 'set null',
		}),
		status: overtimeAuthorizationStatus('status').default('ACTIVE').notNull(),
		notes: text('notes'),
		createdAt: timestamp('created_at').defaultNow().notNull(),
		updatedAt: timestamp('updated_at')
			.defaultNow()
			.$onUpdate(() => /* @__PURE__ */ new Date())
			.notNull(),
	},
	(table) => [
		uniqueIndex('overtime_authorization_employee_date_uniq').on(
			table.employeeId,
			table.dateKey,
		),
		index('overtime_authorization_org_date_idx').on(table.organizationId, table.dateKey),
		index('overtime_authorization_employee_status_idx').on(table.employeeId, table.status),
	],
);

/**
 * Overtime authorization relations.
 */
export const overtimeAuthorizationRelations = relations(overtimeAuthorization, ({ one }) => ({
	organization: one(organization, {
		fields: [overtimeAuthorization.organizationId],
		references: [organization.id],
	}),
	employee: one(employee, {
		fields: [overtimeAuthorization.employeeId],
		references: [employee.id],
	}),
	authorizedByUser: one(user, {
		fields: [overtimeAuthorization.authorizedByUserId],
		references: [user.id],
		relationName: 'overtimeAuthorizationApprovedBy',
	}),
}));

/**
 * Payroll run header table.
 */
export const payrollRun = pgTable('payroll_run', {
	id: text('id')
		.primaryKey()
		.$defaultFn(() => randomUUID()),
	organizationId: text('organization_id')
		.notNull()
		.references(() => organization.id, { onDelete: 'cascade' }),
	periodStart: timestamp('period_start').notNull(),
	periodEnd: timestamp('period_end').notNull(),
	paymentFrequency: paymentFrequency('payment_frequency').notNull(),
	status: payrollRunStatus('status').default('DRAFT').notNull(),
	totalAmount: numeric('total_amount', { precision: 12, scale: 2 }).default('0').notNull(),
	employeeCount: integer('employee_count').default(0).notNull(),
	/** Snapshot of fiscal totals for the run */
	taxSummary: jsonb('tax_summary').$type<Record<string, unknown>>(),
	/** Snapshot of holiday notices persisted at processing time */
	holidayNotices: jsonb('holiday_notices').$type<Record<string, unknown>[]>().default([]),
	processedAt: timestamp('processed_at'),
	createdAt: timestamp('created_at').defaultNow().notNull(),
	updatedAt: timestamp('updated_at')
		.defaultNow()
		.$onUpdate(() => /* @__PURE__ */ new Date())
		.notNull(),
});

/**
 * Payroll run line items per employee.
 */
export const payrollRunEmployee = pgTable('payroll_run_employee', {
	id: text('id')
		.primaryKey()
		.$defaultFn(() => randomUUID()),
	payrollRunId: text('payroll_run_id')
		.notNull()
		.references(() => payrollRun.id, { onDelete: 'cascade' }),
	employeeId: text('employee_id')
		.notNull()
		.references(() => employee.id, { onDelete: 'cascade' }),
	hoursWorked: numeric('hours_worked', { precision: 10, scale: 2 }).default('0').notNull(),
	hourlyPay: numeric('hourly_pay', { precision: 10, scale: 2 }).default('0').notNull(),
	totalPay: numeric('total_pay', { precision: 12, scale: 2 }).default('0').notNull(),
	normalHours: numeric('normal_hours', { precision: 10, scale: 2 }).default('0').notNull(),
	normalPay: numeric('normal_pay', { precision: 12, scale: 2 }).default('0').notNull(),
	overtimeDoubleHours: numeric('overtime_double_hours', { precision: 10, scale: 2 })
		.default('0')
		.notNull(),
	overtimeDoublePay: numeric('overtime_double_pay', { precision: 12, scale: 2 })
		.default('0')
		.notNull(),
	overtimeTripleHours: numeric('overtime_triple_hours', { precision: 10, scale: 2 })
		.default('0')
		.notNull(),
	overtimeTriplePay: numeric('overtime_triple_pay', { precision: 12, scale: 2 })
		.default('0')
		.notNull(),
	authorizedOvertimeHours: numeric('authorized_overtime_hours', { precision: 10, scale: 2 })
		.default('0')
		.notNull(),
	unauthorizedOvertimeHours: numeric('unauthorized_overtime_hours', {
		precision: 10,
		scale: 2,
	})
		.default('0')
		.notNull(),
	sundayPremiumAmount: numeric('sunday_premium_amount', { precision: 12, scale: 2 })
		.default('0')
		.notNull(),
	mandatoryRestDayPremiumAmount: numeric('mandatory_rest_day_premium_amount', {
		precision: 12,
		scale: 2,
	})
		.default('0')
		.notNull(),
	vacationDaysPaid: integer('vacation_days_paid').default(0).notNull(),
	vacationPayAmount: numeric('vacation_pay_amount', { precision: 12, scale: 2 })
		.default('0')
		.notNull(),
	vacationPremiumAmount: numeric('vacation_premium_amount', { precision: 12, scale: 2 })
		.default('0')
		.notNull(),
	/** Snapshot of fiscal breakdown for the employee line */
	taxBreakdown: jsonb('tax_breakdown').$type<Record<string, unknown>>(),
	periodStart: timestamp('period_start').notNull(),
	periodEnd: timestamp('period_end').notNull(),
	createdAt: timestamp('created_at').defaultNow().notNull(),
	updatedAt: timestamp('updated_at')
		.defaultNow()
		.$onUpdate(() => /* @__PURE__ */ new Date())
		.notNull(),
});

/**
 * PTU run header table.
 */
export const ptuRun = pgTable(
	'ptu_run',
	{
		id: text('id')
			.primaryKey()
			.$defaultFn(() => randomUUID()),
		organizationId: text('organization_id')
			.notNull()
			.references(() => organization.id, { onDelete: 'cascade' }),
		fiscalYear: integer('fiscal_year').notNull(),
		paymentDate: timestamp('payment_date').notNull(),
		taxableIncome: numeric('taxable_income', { precision: 14, scale: 2 })
			.default('0')
			.notNull(),
		ptuPercentage: numeric('ptu_percentage', { precision: 6, scale: 4 })
			.default('0.1')
			.notNull(),
		includeInactive: boolean('include_inactive').default(false).notNull(),
		status: ptuRunStatus('status').default('DRAFT').notNull(),
		totalAmount: numeric('total_amount', { precision: 14, scale: 2 }).default('0').notNull(),
		employeeCount: integer('employee_count').default(0).notNull(),
		taxSummary: jsonb('tax_summary').$type<Record<string, unknown>>(),
		settingsSnapshot: jsonb('settings_snapshot').$type<Record<string, unknown>>(),
		processedAt: timestamp('processed_at'),
		cancelledAt: timestamp('cancelled_at'),
		cancelReason: text('cancel_reason'),
		createdAt: timestamp('created_at').defaultNow().notNull(),
		updatedAt: timestamp('updated_at')
			.defaultNow()
			.$onUpdate(() => /* @__PURE__ */ new Date())
			.notNull(),
	},
	(table) => [
		index('ptu_run_org_idx').on(table.organizationId),
		index('ptu_run_year_idx').on(table.organizationId, table.fiscalYear),
	],
);

/**
 * PTU run line items per employee.
 */
export const ptuRunEmployee = pgTable(
	'ptu_run_employee',
	{
		id: text('id')
			.primaryKey()
			.$defaultFn(() => randomUUID()),
		ptuRunId: text('ptu_run_id')
			.notNull()
			.references(() => ptuRun.id, { onDelete: 'cascade' }),
		employeeId: text('employee_id')
			.notNull()
			.references(() => employee.id, { onDelete: 'cascade' }),
		isEligible: boolean('is_eligible').default(true).notNull(),
		eligibilityReasons: jsonb('eligibility_reasons').$type<string[]>().default([]).notNull(),
		daysCounted: integer('days_counted').default(0).notNull(),
		dailyQuota: numeric('daily_quota', { precision: 10, scale: 2 }).default('0').notNull(),
		annualSalaryBase: numeric('annual_salary_base', { precision: 14, scale: 2 })
			.default('0')
			.notNull(),
		ptuByDays: numeric('ptu_by_days', { precision: 14, scale: 2 }).default('0').notNull(),
		ptuBySalary: numeric('ptu_by_salary', { precision: 14, scale: 2 }).default('0').notNull(),
		ptuPreCap: numeric('ptu_pre_cap', { precision: 14, scale: 2 }).default('0').notNull(),
		capThreeMonths: numeric('cap_three_months', { precision: 14, scale: 2 })
			.default('0')
			.notNull(),
		capAvgThreeYears: numeric('cap_avg_three_years', { precision: 14, scale: 2 })
			.default('0')
			.notNull(),
		capFinal: numeric('cap_final', { precision: 14, scale: 2 }).default('0').notNull(),
		ptuFinal: numeric('ptu_final', { precision: 14, scale: 2 }).default('0').notNull(),
		exemptAmount: numeric('exempt_amount', { precision: 14, scale: 2 }).default('0').notNull(),
		taxableAmount: numeric('taxable_amount', { precision: 14, scale: 2 })
			.default('0')
			.notNull(),
		withheldIsr: numeric('withheld_isr', { precision: 14, scale: 2 }).default('0').notNull(),
		netAmount: numeric('net_amount', { precision: 14, scale: 2 }).default('0').notNull(),
		warnings: jsonb('warnings').$type<Record<string, unknown>[]>().default([]).notNull(),
		createdAt: timestamp('created_at').defaultNow().notNull(),
		updatedAt: timestamp('updated_at')
			.defaultNow()
			.$onUpdate(() => /* @__PURE__ */ new Date())
			.notNull(),
	},
	(table) => [
		index('ptu_run_employee_run_idx').on(table.ptuRunId),
		index('ptu_run_employee_employee_idx').on(table.employeeId),
	],
);

/**
 * PTU history table (manual or processed history by year).
 */
export const ptuHistory = pgTable(
	'ptu_history',
	{
		id: text('id')
			.primaryKey()
			.$defaultFn(() => randomUUID()),
		organizationId: text('organization_id')
			.notNull()
			.references(() => organization.id, { onDelete: 'cascade' }),
		employeeId: text('employee_id')
			.notNull()
			.references(() => employee.id, { onDelete: 'cascade' }),
		fiscalYear: integer('fiscal_year').notNull(),
		amount: numeric('amount', { precision: 14, scale: 2 }).default('0').notNull(),
		createdAt: timestamp('created_at').defaultNow().notNull(),
		updatedAt: timestamp('updated_at')
			.defaultNow()
			.$onUpdate(() => /* @__PURE__ */ new Date())
			.notNull(),
	},
	(table) => [
		index('ptu_history_employee_idx').on(table.employeeId),
		index('ptu_history_org_idx').on(table.organizationId),
		uniqueIndex('ptu_history_employee_year_uniq').on(table.employeeId, table.fiscalYear),
	],
);

/**
 * Aguinaldo run header table.
 */
export const aguinaldoRun = pgTable(
	'aguinaldo_run',
	{
		id: text('id')
			.primaryKey()
			.$defaultFn(() => randomUUID()),
		organizationId: text('organization_id')
			.notNull()
			.references(() => organization.id, { onDelete: 'cascade' }),
		calendarYear: integer('calendar_year').notNull(),
		paymentDate: timestamp('payment_date').notNull(),
		includeInactive: boolean('include_inactive').default(false).notNull(),
		status: aguinaldoRunStatus('status').default('DRAFT').notNull(),
		totalAmount: numeric('total_amount', { precision: 14, scale: 2 }).default('0').notNull(),
		employeeCount: integer('employee_count').default(0).notNull(),
		taxSummary: jsonb('tax_summary').$type<Record<string, unknown>>(),
		settingsSnapshot: jsonb('settings_snapshot').$type<Record<string, unknown>>(),
		processedAt: timestamp('processed_at'),
		cancelledAt: timestamp('cancelled_at'),
		cancelReason: text('cancel_reason'),
		createdAt: timestamp('created_at').defaultNow().notNull(),
		updatedAt: timestamp('updated_at')
			.defaultNow()
			.$onUpdate(() => /* @__PURE__ */ new Date())
			.notNull(),
	},
	(table) => [
		index('aguinaldo_run_org_idx').on(table.organizationId),
		index('aguinaldo_run_year_idx').on(table.organizationId, table.calendarYear),
	],
);

/**
 * Aguinaldo run line items per employee.
 */
export const aguinaldoRunEmployee = pgTable(
	'aguinaldo_run_employee',
	{
		id: text('id')
			.primaryKey()
			.$defaultFn(() => randomUUID()),
		aguinaldoRunId: text('aguinaldo_run_id')
			.notNull()
			.references(() => aguinaldoRun.id, { onDelete: 'cascade' }),
		employeeId: text('employee_id')
			.notNull()
			.references(() => employee.id, { onDelete: 'cascade' }),
		isEligible: boolean('is_eligible').default(true).notNull(),
		eligibilityReasons: jsonb('eligibility_reasons').$type<string[]>().default([]).notNull(),
		daysCounted: integer('days_counted').default(0).notNull(),
		dailySalaryBase: numeric('daily_salary_base', { precision: 10, scale: 2 })
			.default('0')
			.notNull(),
		aguinaldoDaysPolicy: integer('aguinaldo_days_policy').default(15).notNull(),
		yearDays: integer('year_days').default(365).notNull(),
		grossAmount: numeric('gross_amount', { precision: 14, scale: 2 }).default('0').notNull(),
		exemptAmount: numeric('exempt_amount', { precision: 14, scale: 2 }).default('0').notNull(),
		taxableAmount: numeric('taxable_amount', { precision: 14, scale: 2 })
			.default('0')
			.notNull(),
		withheldIsr: numeric('withheld_isr', { precision: 14, scale: 2 }).default('0').notNull(),
		netAmount: numeric('net_amount', { precision: 14, scale: 2 }).default('0').notNull(),
		warnings: jsonb('warnings').$type<Record<string, unknown>[]>().default([]).notNull(),
		createdAt: timestamp('created_at').defaultNow().notNull(),
		updatedAt: timestamp('updated_at')
			.defaultNow()
			.$onUpdate(() => /* @__PURE__ */ new Date())
			.notNull(),
	},
	(table) => [
		index('aguinaldo_run_employee_run_idx').on(table.aguinaldoRunId),
		index('aguinaldo_run_employee_employee_idx').on(table.employeeId),
	],
);
