/**
 * Client functions for mobile app API communication.
 * All functions use the Eden Treaty client for type-safe API calls.
 *
 * @module lib/client-functions
 */

import type { AttendanceRecord, AttendanceType, Device, Location } from '@sen-checkin/types';

import { API_BASE_URL, api, authedFetchForEden } from './api';
import { getAccessToken } from './auth-client';
import type { AttendanceQueryParams, ListQueryParams } from './query-keys';

// ============================================================================
// Common Types
// ============================================================================

/**
 * Standard paginated response shape from API endpoints.
 */
type PaginatedResponse<T> = {
	/** Array of data items */
	data: T[];
	/** Pagination metadata */
	pagination: {
		/** Total count of available records */
		total: number;
		/** Number of records per page */
		limit: number;
		/** Number of records skipped */
		offset: number;
		/** Whether more records exist beyond this page */
		hasMore?: boolean;
	};
};

// ============================================================================
// Device Types
// ============================================================================

/**
 * Extended device type including organization relationship.
 */
export type DeviceDetail = Device & { organizationId?: string | null };

/**
 * Input payload for registering a device.
 */
export interface RegisterDeviceInput {
	/** Stable device code generated by the mobile client */
	code: string;
	/** Friendly device name */
	name?: string;
	/** Device type label (e.g., iPhone, Android) */
	deviceType?: string;
	/** Platform identifier (ios, android) */
	platform?: string;
	/** Organization ID to register device under */
	organizationId?: string | null;
}

/**
 * Response from device registration endpoint.
 */
export interface RegisterDeviceResponse {
	/** Registered device details */
	device: DeviceDetail;
	/** Whether this is a newly created device */
	isNew: boolean;
}

/**
 * Fetch a paginated list of locations using the Eden Treaty client.
 *
 * @param params - Optional filters for search, organization, and pagination
 * @returns Locations with pagination metadata
 * @throws Error when the API response is not OK
 */
export async function fetchLocationsList(
	params?: ListQueryParams & { organizationId?: string | null },
): Promise<PaginatedResponse<Location>> {
	const limit = params?.limit ?? 100;
	const offset = params?.offset ?? 0;

	// Build query object conditionally to avoid sending "undefined" strings
	const query: {
		limit: number;
		offset: number;
		search?: string;
		organizationId?: string;
	} = {
		limit,
		offset,
	};

	if (params?.search) {
		query.search = params.search;
	}

	if (params?.organizationId) {
		query.organizationId = params.organizationId;
	}

	const { data, error } = await api.locations.get({
		$query: query,
	});

	if (error) {
		console.error('[fetchLocationsList] Eden Treaty error:', error);
		throw new Error('Failed to load locations');
	}

	// Type guard: check if data has the expected shape
	if (!data || 'error' in data) {
		const errorMessage = data && 'error' in data ? String(data.error) : 'Unknown error';
		console.error('[fetchLocationsList] API error:', errorMessage);
		throw new Error('Failed to load locations');
	}

	return {
		data: (data.data ?? []) as Location[],
		pagination: data.pagination ?? {
			total: 0,
			limit,
			offset,
		},
	};
}

/**
 * Device status enumeration matching API schema.
 */
export type DeviceStatus = 'ONLINE' | 'OFFLINE' | 'MAINTENANCE';

/**
 * Query parameters for fetching devices list.
 */
export interface DevicesListParams extends ListQueryParams {
	/** Filter devices by name or code */
	search?: string;
	/** Filter by location ID */
	locationId?: string;
	/** Filter by device status */
	status?: DeviceStatus;
	/** Filter by organization ID */
	organizationId?: string | null;
}

/**
 * Fetch the list of devices with optional filters using the Eden Treaty client.
 *
 * @param params - Filter and pagination options
 * @returns Devices with pagination metadata
 * @throws Error when the API response is not OK
 */
export async function fetchDevicesList(
	params?: DevicesListParams,
): Promise<PaginatedResponse<Device>> {
	const limit = params?.limit ?? 100;
	const offset = params?.offset ?? 0;

	// Build query object conditionally to avoid sending "undefined" strings
	const query: {
		limit: number;
		offset: number;
		search?: string;
		locationId?: string;
		status?: DeviceStatus;
		organizationId?: string;
	} = {
		limit,
		offset,
	};

	if (params?.search) {
		query.search = params.search;
	}

	if (params?.locationId) {
		query.locationId = params.locationId;
	}

	if (params?.status) {
		query.status = params.status;
	}

	if (params?.organizationId) {
		query.organizationId = params.organizationId;
	}

	const { data, error } = await api.devices.get({
		$query: query,
	});

	if (error) {
		console.error('[fetchDevicesList] Eden Treaty error:', error);
		throw new Error('Failed to load devices');
	}

	if (!data || 'error' in data) {
		const errorMessage = data && 'error' in data ? String(data.error) : 'Unknown error';
		console.error('[fetchDevicesList] API error:', errorMessage);
		throw new Error('Failed to load devices');
	}

	return {
		data: (data.data ?? []) as Device[],
		pagination: data.pagination ?? {
			total: 0,
			limit,
			offset,
		},
	};
}

/**
 * Retrieve a single device by ID using the Eden Treaty client.
 *
 * @param deviceId - Device identifier (UUID)
 * @returns Device detail or null if not found
 * @throws Error when the API response is not OK
 */
export async function fetchDeviceDetail(deviceId: string): Promise<DeviceDetail | null> {
	const deviceEndpoint = api.devices[deviceId];
	if (!deviceEndpoint) {
		throw new Error('Invalid device endpoint');
	}

	const { data, error } = await deviceEndpoint.get();

	if (error) {
		console.error('[fetchDeviceDetail] Eden Treaty error:', error);
		throw new Error('Failed to load device');
	}

	if (!data || 'error' in data) {
		const errorMessage = data && 'error' in data ? String(data.error) : 'Unknown error';
		console.error('[fetchDeviceDetail] API error:', errorMessage);
		throw new Error('Failed to load device');
	}

	return (data.data as DeviceDetail) ?? null;
}

/**
 * Register or upsert a device using a stable device code via the Eden Treaty client.
 * When the code already exists for the same organization, metadata is refreshed.
 * Otherwise, a new device is created.
 *
 * @param input - Registration payload including stable code and metadata
 * @returns Registered device payload and creation flag from the API
 * @throws Error when the API call fails or returns no data
 */
export async function registerDevice(input: RegisterDeviceInput): Promise<RegisterDeviceResponse> {
	const { data, error } = await api.devices.register.post({
		code: input.code,
		name: input.name,
		deviceType: input.deviceType,
		platform: input.platform,
		organizationId: input.organizationId ?? undefined,
	});

	if (error) {
		console.error('[registerDevice] Eden Treaty error:', error);
		throw new Error('Failed to register device');
	}

	if (!data || 'error' in data) {
		const errorMessage = data && 'error' in data ? String(data.error) : 'Unknown error';
		console.error('[registerDevice] API error:', errorMessage);
		throw new Error('Failed to register device');
	}

	if (!data.data) {
		throw new Error('Device registration returned no data');
	}

	return {
		device: data.data as DeviceDetail,
		isNew: Boolean(data.isNew),
	};
}

/**
 * Payload for updating device settings.
 */
export interface UpdateDevicePayload {
	/** Device friendly name */
	name?: string | null;
	/** Location ID reference */
	locationId?: string | null;
}

/**
 * Update device metadata (name/location) via the Eden Treaty client.
 *
 * @param deviceId - Device identifier (UUID)
 * @param payload - Fields to update (name, locationId)
 * @returns Updated device payload
 * @throws Error when the API response is not OK or lacks data
 */
export async function updateDeviceSettings(
	deviceId: string,
	payload: UpdateDevicePayload,
): Promise<DeviceDetail> {
	const deviceEndpoint = api.devices[deviceId];
	if (!deviceEndpoint) {
		throw new Error('Invalid device endpoint');
	}

	const { data, error } = await deviceEndpoint.put(payload);

	if (error) {
		console.error('[updateDeviceSettings] Eden Treaty error:', error);
		throw new Error('Failed to update device settings');
	}

	if (!data || 'error' in data) {
		const errorMessage = data && 'error' in data ? String(data.error) : 'Unknown error';
		console.error('[updateDeviceSettings] API error:', errorMessage);
		throw new Error('Failed to update device settings');
	}

	if (!data.data) {
		throw new Error('Device update returned no data');
	}

	return data.data as DeviceDetail;
}

/**
 * Send a heartbeat to mark the device as online.
 * Updates the device's lastHeartbeat timestamp and sets status to ONLINE.
 *
 * Returns null if no access token is available (e.g., before OAuth 2.0 device
 * authorization completes). This allows the heartbeat to be called at any time
 * without failing during the initial authentication flow.
 *
 * Note: Uses direct fetch instead of Eden Treaty due to nested dynamic route limitations.
 *
 * @param deviceId - Device identifier (UUID) to ping
 * @returns Updated device payload with the latest heartbeat timestamp, or null if not authenticated
 * @throws Error when the API response is not OK or lacks data (after authentication)
 */
export async function sendDeviceHeartbeat(deviceId: string): Promise<DeviceDetail | null> {
	// Check if we have an access token before attempting the request
	// This prevents errors during the initial OAuth 2.0 device authorization flow
	const accessToken = getAccessToken();
	if (!accessToken) {
		console.log('[sendDeviceHeartbeat] Skipping heartbeat - no access token available yet');
		return null;
	}

	const response = await authedFetchForEden(`${API_BASE_URL}/devices/${deviceId}/heartbeat`, {
		method: 'POST',
	});

	if (!response.ok) {
		const errorText = await response.text().catch(() => 'Unknown error');
		console.error('[sendDeviceHeartbeat] API error:', response.status, errorText);
		throw new Error('Failed to send device heartbeat');
	}

	const json = (await response.json()) as { data?: DeviceDetail; error?: string };

	if ('error' in json && json.error) {
		console.error('[sendDeviceHeartbeat] API error:', json.error);
		throw new Error('Failed to send device heartbeat');
	}

	if (!json.data) {
		throw new Error('Heartbeat response missing data');
	}

	return json.data;
}

/**
 * Query parameters for fetching attendance records.
 */
export interface AttendanceListParams extends AttendanceQueryParams {
	/** Filter by organization ID */
	organizationId?: string | null;
}

/**
 * Fetch attendance records with optional filters via the Eden Treaty client.
 * Supports filtering by employee, device, type, and date range.
 *
 * @param params - Attendance query filters
 * @returns Attendance records with pagination info
 * @throws Error when the API response is not OK
 */
export async function fetchAttendanceList(
	params?: AttendanceListParams,
): Promise<PaginatedResponse<AttendanceRecord>> {
	const limit = params?.limit ?? 50;
	const offset = params?.offset ?? 0;

	// Build query object conditionally to avoid sending "undefined" strings
	const query: {
		limit: number;
		offset: number;
		employeeId?: string;
		deviceId?: string;
		type?: AttendanceType;
		fromDate?: Date;
		toDate?: Date;
		organizationId?: string;
	} = {
		limit,
		offset,
	};

	if (params?.employeeId) {
		query.employeeId = params.employeeId;
	}

	if (params?.deviceId) {
		query.deviceId = params.deviceId;
	}

	if (params?.type) {
		query.type = params.type;
	}

	if (params?.fromDate) {
		query.fromDate = params.fromDate;
	}

	if (params?.toDate) {
		query.toDate = params.toDate;
	}

	if (params?.organizationId) {
		query.organizationId = params.organizationId;
	}

	const { data, error } = await api.attendance.get({
		$query: query,
	});

	if (error) {
		console.error('[fetchAttendanceList] Eden Treaty error:', error);
		throw new Error('Failed to load attendance records');
	}

	if (!data || 'error' in data) {
		const errorMessage = data && 'error' in data ? String(data.error) : 'Unknown error';
		console.error('[fetchAttendanceList] API error:', errorMessage);
		throw new Error('Failed to load attendance records');
	}

	return {
		data: (data.data ?? []) as AttendanceRecord[],
		pagination: data.pagination ?? {
			total: 0,
			limit,
			offset,
		},
	};
}

/**
 * Input payload for creating an attendance record.
 */
export interface CreateAttendanceInput {
	/** Employee ID (UUID) */
	employeeId: string;
	/** Device ID (UUID) */
	deviceId: string;
	/** Attendance type (CHECK_IN or CHECK_OUT) */
	type: AttendanceType;
	/** Additional metadata (optional) */
	metadata?: Record<string, unknown>;
	/** Timestamp of the attendance event (defaults to now) */
	timestamp?: Date;
}

/**
 * Create an attendance record after successful face verification via the Eden Treaty client.
 *
 * @param input - Attendance payload including employeeId, deviceId, type, and optional metadata
 * @returns The created attendance record
 * @throws Error when the API response is not OK or lacks data
 */
export async function createAttendanceRecord(
	input: CreateAttendanceInput,
): Promise<AttendanceRecord> {
	const timestamp = input.timestamp ?? new Date();

	const { data, error } = await api.attendance.post({
		employeeId: input.employeeId,
		deviceId: input.deviceId,
		type: input.type,
		metadata: input.metadata,
		timestamp,
	});

	if (error) {
		console.error('[createAttendanceRecord] Eden Treaty error:', error);
		throw new Error('Failed to create attendance record');
	}

	if (!data || 'error' in data) {
		const errorMessage = data && 'error' in data ? String(data.error) : 'Unknown error';
		console.error('[createAttendanceRecord] API error:', errorMessage);
		throw new Error('Failed to create attendance record');
	}

	if (!data.data) {
		throw new Error('Attendance response missing data');
	}

	return data.data as AttendanceRecord;
}
